"""Build INTERVIEW_MAP.md: every theory question in ../ai_interview_prep, and the notebooks that practise it.

    python build_interview_map.py            # write INTERVIEW_MAP.md
    python build_interview_map.py --check    # only validate: fail if a notebook cites an unknown question ID

Each notebook has a cell headed "## Interview questions this notebook answers" with a
table of backticked question IDs (`rg00`, `tn12`, ...). This script reads those cells,
reads the question bank straight from ai_interview_prep/js/bank-*.js, and writes the
reverse map, so from any theory question you can jump to the code that makes it concrete.
"""

from __future__ import annotations

import json
import re
import sys
from collections import defaultdict
from pathlib import Path

HERE = Path(__file__).resolve().parent
BANK_DIR = HERE.parent / "ai_interview_prep" / "js"
HEADING = "## Interview questions this notebook answers"

TOPIC_NAMES = {
    "foundations": "Foundations", "transformers": "Transformers", "training": "Training & tuning",
    "inference": "Inference & serving", "prompting": "Prompting & context", "rag": "RAG",
    "vectors": "Vectors & search", "agents": "Agents & tools", "eval": "Evaluation",
    "safety": "Safety & guardrails", "production": "Production & cost", "prodops": "Production drills",
    "data": "Data engineering", "sysdesign": "System design", "behavioural": "Behavioural",
    "tooling": "Tooling",
}

CARD = re.compile(r"id:\s*'([a-z]{2}\d{2})'\s*,\s*topic:\s*'([a-z_-]+)'\s*,\s*level:\s*(\d+)\s*,\s*"
                  r"q:\s*'((?:[^'\\]|\\.)*)'", re.S)


def load_bank() -> dict[str, dict]:
    bank = {}
    for f in sorted(BANK_DIR.glob("bank-*.js")):
        for qid, topic, level, q in CARD.findall(f.read_text(encoding="utf-8")):
            q = re.sub(r"\s+", " ", q.replace("\\'", "'").replace('\\"', '"'))
            bank[qid] = {"topic": topic, "level": int(level), "q": q}
    return bank


def notebook_links() -> dict[str, list[str]]:
    """question id -> notebooks (posix paths relative to this folder)."""
    links = defaultdict(list)
    for nb_path in sorted(HERE.rglob("*.ipynb")):
        if ".venv" in nb_path.parts or ".ipynb_checkpoints" in nb_path.parts:
            continue
        nb = json.loads(nb_path.read_text(encoding="utf-8"))
        for cell in nb.get("cells", []):
            src = "".join(cell.get("source", [])) if isinstance(cell.get("source"), list) else cell.get("source", "")
            if cell.get("cell_type") == "markdown" and src.lstrip().startswith(HEADING):
                for qid in dict.fromkeys(re.findall(r"`([a-z]{2}\d{2})`", src)):
                    links[qid].append(nb_path.relative_to(HERE).as_posix())
    return links


def title_of(rel: str) -> str:
    stem = Path(rel).stem
    return re.sub(r"^\d+_", "", stem).replace("_", " ")


def main() -> int:
    bank = load_bank()
    links = notebook_links()
    unknown = sorted(q for q in links if q not in bank)
    if unknown:
        print("Notebooks cite question IDs that are not in the bank:")
        for q in unknown:
            print(f"  {q}: {', '.join(links[q])}")
    if "--check" in sys.argv:
        print(f"{len(bank)} questions in the bank, {sum(1 for q in links if q in bank)} linked from notebooks")
        return 1 if unknown else 0

    by_topic = defaultdict(list)
    for qid, card in bank.items():
        by_topic[card["topic"]].append(qid)
    order = [t for t in TOPIC_NAMES if t in by_topic] + sorted(t for t in by_topic if t not in TOPIC_NAMES)
    linked_total = sum(1 for q in bank if q in links)

    out = ["# Interview map — theory question → runnable notebook", "",
           "Generated by `python build_interview_map.py` from the question bank in "
           "[`../ai_interview_prep`](../ai_interview_prep/index.html) and the "
           "*Interview questions this notebook answers* table at the top of every notebook. "
           "Re-run it after adding or editing notebooks.", "",
           f"**{linked_total} of {len(bank)} questions** have at least one notebook that makes the answer "
           "concrete. The rest (behavioural, many system-design and production-drill scenarios) are "
           "best practised out loud with the theory bank's mock-interview mode.", "",
           "| Topic | Questions | With a notebook |", "|---|---:|---:|"]
    for t in order:
        qs = by_topic[t]
        n = sum(1 for q in qs if q in links)
        out.append(f"| [{TOPIC_NAMES.get(t, t)}](#{t}) | {len(qs)} | {n} |")
    out.append("")
    for t in order:
        out += [f'<a id="{t}"></a>', "", f"## {TOPIC_NAMES.get(t, t)}", "",
                "| ID | Level | Question | Practise it in |", "|---|:-:|---|---|"]
        for qid in sorted(by_topic[t]):
            card = bank[qid]
            nbs = links.get(qid, [])
            where = "<br>".join(f"[{title_of(p)}]({p})" for p in nbs) if nbs else "—"
            q = card["q"].replace("|", "\\|")
            out.append(f"| `{qid}` | {card['level']} | {q} | {where} |")
        out.append("")
    (HERE / "INTERVIEW_MAP.md").write_text("\n".join(out), encoding="utf-8")
    print(f"wrote INTERVIEW_MAP.md: {linked_total}/{len(bank)} questions linked, "
          f"{len(set(p for v in links.values() for p in v))} notebooks cite the bank")
    return 1 if unknown else 0


if __name__ == "__main__":
    sys.exit(main())
