/* ============================================================
   Vectors & search — embeddings, similarity, ANN indexes,
   and the lexical half everyone forgets.
   ============================================================ */
window.QB = (window.QB || []).concat([

{ id: 've01', topic: 'vectors', level: 1,
  q: 'What is cosine similarity, and what are the alternatives?',
  lay: 'Cosine measures the angle between two arrows and ignores their length — so it asks "are these pointing the same way?" rather than "are they the same size?". For meaning, direction is what matters.',
  tech: '<span class="mono">cos(a,b) = (a·b) / (|a||b|)</span>, ranging from −1 to 1. Alternatives: <b>dot product</b> (unnormalised — identical to cosine when vectors are unit-normalised, and faster because it skips the division), <b>Euclidean / L2</b> (straight-line distance; also equivalent to cosine on normalised vectors, since |a−b|² = 2−2cos for unit vectors), <b>Manhattan / L1</b> (rare), <b>Hamming</b> (for binary vectors, extremely fast), <b>Jaccard</b> (for sets, not vectors — used on token sets and MinHash).',
  compare: { cols: ['Cosine', 'Dot product', 'Euclidean (L2)'],
    rows: [
      ['Measures', 'angle only', 'angle and magnitude', 'straight-line distance'],
      ['Range', '−1 to 1', 'unbounded', '0 to ∞'],
      ['Magnitude matters', 'no', 'yes', 'yes'],
      ['On unit vectors', 'the reference', 'identical to cosine', 'a monotone function of cosine'],
      ['Typical use', 'text embeddings', 'when magnitude encodes confidence, e.g. some recommenders', 'clustering, image features'],
      ['Speed', 'one extra normalisation', 'fastest', 'fast']
    ] },
  trap: 'The practical rule: normalise your vectors once at index time, then use dot product. It is the same ranking as cosine and skips a division per comparison — which matters when you are doing millions of them.',
  tags: ['similarity'], orig: 19 },

{ id: 've02', topic: 'vectors', level: 2,
  q: 'When would you use dot product instead of cosine?',
  lay: 'When the length of the arrow means something. In some recommender systems a longer vector means "more popular" or "more confident", and cosine would throw that information away.',
  tech: 'Use dot product when magnitude carries signal: matrix-factorisation recommenders where item vector norms encode popularity, models trained with a dot-product objective (using cosine at query time then mismatches training), or when you deliberately want popularity bias in ranking. Use cosine when only semantic direction matters, which is nearly all text retrieval. Critically: use the metric the embedding model was TRAINED with — most text embedders are trained with cosine, and switching silently degrades quality.',
  trap: 'Vector databases require you to declare the metric at index creation and you usually cannot change it without rebuilding. Getting it wrong is a rebuild, not a config change.',
  tags: ['similarity'], orig: 19 },

{ id: 've03', topic: 'vectors', level: 1,
  q: 'Your vector database has 10 million documents. How does it find the nearest without comparing all 10 million?',
  lay: 'It does not look at everything. It organises the vectors into neighbourhoods first, then only opens the few neighbourhoods nearest your question. It is faster because it looks at less — and occasionally wrong for exactly the same reason.',
  tech: 'Approximate nearest neighbour search. Exact search is O(n·d) per query — 10M × 768 dimensions is roughly 7.7 billion multiply-adds, which is tens to hundreds of milliseconds even vectorised, per query. ANN indexes trade a small amount of recall for orders of magnitude of speed. The two dominant families: <b>graph-based</b> (HNSW — navigate a small-world graph greedily) and <b>partition-based</b> (IVF — cluster the space, search only the nearest cells). Both are usually combined with compression (product quantisation) when memory is the binding constraint.',
  dgm: { nodes: [{ t: '10M vectors' }, { t: 'filter by metadata', s: 'cuts orders of magnitude', k: 'alt' }, { t: 'ANN index', s: 'HNSW or IVF' }, { t: 'top 100 candidates' }, { t: 'rerank', s: 'cross-encoder', k: 'alt' }, { t: 'top 5' }],
    cap: 'Every stage is cheaper per item and looks at fewer items than the last.' },
  trap: 'The answer interviewers most want to hear first is the metadata filter. At 10M documents, cutting the candidate space by tenant, recency or language before similarity is computed does more for latency AND quality than any index tuning.',
  tags: ['ann'], orig: 13 },

{ id: 've04', topic: 'vectors', level: 2,
  q: 'How does HNSW work?',
  lay: 'Imagine a road network with motorways, A-roads and side streets. You start on the motorway and cover a lot of ground fast, then drop to smaller roads as you get close. HNSW builds exactly that: a few long-range links at the top, dense local links at the bottom.',
  tech: 'Hierarchical Navigable Small World. A multi-layer proximity graph: the top layer has few nodes with long-range edges, each lower layer has more nodes and shorter edges, and layer 0 contains everything. Search starts at an entry point in the top layer, greedily walks to the nearest neighbour, then descends a layer and repeats. Parameters: <b>M</b> (edges per node, typically 16–64 — higher means better recall and more memory), <b>ef_construction</b> (candidate list size at build time, higher means a better graph and slower build), <b>ef_search</b> (candidate list at query time — the direct recall/latency dial you tune in production).',
  trap: 'HNSW\'s weakness is memory and mutability: the graph lives in RAM, uses roughly (vector bytes + M × 8) per node, and deletes are usually soft (tombstones) requiring periodic rebuild. If your corpus churns heavily, that maintenance is a real cost.',
  tags: ['hnsw', 'ann'], orig: 50 },

{ id: 've05', topic: 'vectors', level: 2,
  q: 'How does IVF work, and how does it compare to HNSW?',
  lay: 'Divide the space into a few thousand neighbourhoods with k-means, and remember which neighbourhood each vector lives in. At query time, work out which handful of neighbourhoods your question is nearest to, and only look inside those.',
  tech: 'Inverted File index. Build: run k-means to get nlist centroids and assign every vector to its nearest cell. Query: find the nprobe nearest centroids and scan only those cells. <b>nprobe</b> is the recall/latency dial. Missing neighbours happens when a true nearest neighbour sits just across a cell boundary in a cell you did not probe — raising nprobe recovers them at proportional cost. Usually paired with product quantisation as IVF-PQ.',
  compare: { cols: ['HNSW', 'IVF(-PQ)'],
    rows: [
      ['Structure', 'multi-layer proximity graph', 'k-means partitions of the space'],
      ['Memory', 'high — graph plus full vectors in RAM', 'low with PQ — can be an order of magnitude smaller'],
      ['Build time', 'slow', 'fast (one k-means pass)'],
      ['Query speed', 'fastest at high recall', 'good; tunable with nprobe'],
      ['Recall dial', 'ef_search', 'nprobe'],
      ['Updates', 'incremental insert; deletes are tombstones', 'easy inserts; centroids drift, needs periodic retraining'],
      ['Best for', 'up to tens of millions, memory available', 'hundreds of millions, memory constrained']
    ] },
  trap: 'IVF centroids are trained on a sample of your data. If the corpus distribution shifts materially, the partitioning degrades and recall drops with no error — you need to retrain periodically and monitor recall against a fixed probe set.',
  tags: ['ivf', 'ann'], orig: 50 },

{ id: 've06', topic: 'vectors', level: 3,
  q: 'What is product quantisation?',
  lay: 'Chop each long list of numbers into eight short pieces, and replace each piece with the nearest entry from a small codebook. Instead of storing 768 precise numbers you store eight small codes — a huge saving, and a slightly blurry vector.',
  tech: 'Split a d-dimensional vector into m subvectors; run k-means (typically 256 centroids) on each subspace independently; store m byte codes instead of d floats. A 768-dim float32 vector is 3,072 bytes; with m = 96 it becomes 96 bytes — a 32× reduction. Distances are computed with precomputed lookup tables between the query subvectors and each codebook, so scoring is table lookups and additions rather than multiplications. Variants: OPQ rotates the space first to decorrelate subspaces; scalar quantisation (float32 → int8) is simpler at ~4× with less loss.',
  code: `# memory is the constraint that actually decides your index
n, d = 100_000_000, 768
raw   = n * d * 4 / 1024**3                 # float32
sq    = n * d * 1 / 1024**3                 # int8 scalar quantisation
pq    = n * 96      / 1024**3               # PQ, m=96 bytes per vector
print(f"{raw:.0f} GB raw, {sq:.0f} GB int8, {pq:.0f} GB PQ")
# ~286 GB raw -> ~72 GB int8 -> ~9 GB PQ`,
  trap: 'PQ loses accuracy, so the standard pattern is PQ for the coarse search and a rerank pass over the top few hundred using the EXACT vectors (kept on disk or in a separate store). You get the memory saving and most of the recall back.',
  tags: ['pq', 'ann'], orig: 50 },

{ id: 've07', topic: 'vectors', level: 2,
  q: 'What is the recall/latency trade-off in ANN, and how do you tune it?',
  lay: 'Look at more candidates, find more of the right answers, take longer. That is the whole dial. The job is to find the point where extra looking stops paying.',
  tech: 'Measure recall@k against exact brute-force search on a sample of real queries — that is the ground truth, and computing it on 1,000 queries is cheap. Then sweep the dial (ef_search for HNSW, nprobe for IVF) and plot recall against p95 latency. Pick the knee. Typical production targets are 0.95–0.99 recall@10. Two things people forget: recall must be re-measured after any index rebuild or corpus growth, and end-to-end quality can be insensitive to recall above a point because the reranker fixes ordering anyway.',
  trap: 'ANN recall is not the same as retrieval quality. You can have 0.99 recall against brute force and still retrieve the wrong documents, because brute force over bad embeddings is still bad. Measure both: ANN recall against exact search, and retrieval quality against human labels.',
  tags: ['ann', 'tuning'], orig: 50 },

{ id: 've08', topic: 'vectors', level: 2,
  q: 'What is BM25 and how does it work?',
  lay: 'A scoring rule for word matching that asks three things: does this page use the word a lot, is the word rare across all pages, and is the page short enough that the word is clearly what it is about.',
  tech: '<span class="mono">score(q,d) = Σ_t IDF(t) · (tf · (k₁+1)) / (tf + k₁·(1 − b + b·dl/avgdl))</span>. Three ideas: <b>term frequency, saturated</b> — the numerator and denominator together mean the fiftieth mention adds almost nothing, which is what separates BM25 from naive TF-IDF; <b>inverse document frequency</b> — a term in 1 of 8 documents is worth far more than one in 7 of 8, which is why a rare error code dominates a query; <b>length normalisation</b> — b controls how much a long document is penalised. Defaults k₁ = 1.2, b = 0.75 are good almost everywhere.',
  trap: 'The saturation term is the interview answer. Without it, a document repeating "refund" ninety times beats the document that actually answers the question — and that is exactly what happens with plain TF-IDF.',
  tags: ['bm25', 'lexical'], orig: 10 },

{ id: 've09', topic: 'vectors', level: 2,
  q: 'What is Elasticsearch and what is it actually good at?',
  lay: 'A search engine built on an inverted index — the index at the back of a book, at scale. It is excellent at word matching, filtering, counting and explaining itself, and it now does vectors too.',
  tech: 'A distributed search engine over Lucene. Core concepts: an <b>index</b> (a collection with a mapping/schema), split into <b>primary shards</b> (each a self-contained Lucene index, count fixed at creation), each with <b>replicas</b> (availability and read throughput). Shards are made of immutable <b>segments</b>; writes create new segments and deletes are tombstones, with periodic merging. It is <b>near</b> real-time: a document is searchable after the next refresh, one second by default. The <b>analyzer</b> chain turns text into terms, and the same chain must run on the query. <b>Filter context</b> answers yes/no, is cached as a bitset and is dramatically faster than scored query context.',
  trap: 'Shard count is the classic production mistake — it is fixed at index creation and cannot be changed without reindexing. Aim for 10–50 GB per shard and think before you type.',
  tags: ['elasticsearch', 'lexical'], orig: 10 },

{ id: 've10', topic: 'vectors', level: 2,
  q: 'What is an inverted index?',
  lay: 'The index at the back of a book. Instead of reading all 400 pages looking for "refund", you look up "refund" once and it tells you pages 12, 88 and 203.',
  tech: 'A map from term → posting list of (document id, term frequency, positions). Building it: analyse each document into terms and append to each term\'s list. Querying: intersect or union the posting lists for the query terms, score the survivors with BM25, and return the top k. Posting lists are compressed (delta encoding plus variable-byte or PFOR) and stored sorted so intersection is a merge. Positions enable phrase queries. The whole structure is why lexical search can serve billions of documents on modest hardware.',
  trap: 'The reason it beats vector search on exact identifiers: a rare term has a very short posting list, so finding every document containing "E-4055" is nearly free and completely exact. There is no approximation and no embedding to blur it.',
  tags: ['lexical', 'elasticsearch'], orig: 10 },

{ id: 've11', topic: 'vectors', level: 2,
  q: 'What is an analyzer, and what breaks when it is wrong?',
  lay: 'The pipeline that turns text into searchable words — lowercase it, split it, strip the endings, expand the synonyms. If you use a different pipeline when indexing than when searching, nothing matches and nothing errors.',
  tech: 'Character filters → tokenizer → token filters (lowercase, stop words, stemming, synonyms, ASCII folding, language-specific normalisation). The same chain must apply at index and query time. Common failures: a stemmer applied at index but not at query; a synonym filter at query time only, causing asymmetric matching; the wrong language analyzer, so Arabic diacritics or German compounds are never normalised. Test with the analyze API — feed it a string and see the terms it produces.',
  trap: 'This is the number-one cause of "why does nothing match" in a lexical system, and it is invisible: every query runs successfully and returns zero results. Always inspect the analysed terms before debugging anything else.',
  tags: ['elasticsearch', 'lexical'], orig: 41 },

{ id: 've12', topic: 'vectors', level: 2,
  q: 'Query context versus filter context — why does it matter?',
  lay: 'A query asks "how well does this match?" and computes a score. A filter asks "does this match, yes or no?" and can be cached. Anything that is a hard requirement should be a filter.',
  tech: 'Filter context skips scoring entirely and caches results as a bitset that can be reused across queries, so it is dramatically faster. Everything that is a boolean requirement belongs there: tenant id, date ranges, status, language, permissions. Query context is for the parts where relevance ranking matters — the user\'s search phrase. Putting the tenant id in query context is both slower and, if anyone ever forgets it, a cross-tenant data leak rather than a ranking bug.',
  trap: 'The security framing is what makes this more than a performance tip. A permission expressed as a scoring signal is not a permission.',
  tags: ['elasticsearch', 'security'], orig: 10 },

{ id: 've13', topic: 'vectors', level: 2,
  q: 'Lexical versus dense retrieval — what is the honest comparison?',
  lay: 'Word matching is perfect for codes, names and jargon and blind to paraphrase. Meaning matching is perfect for paraphrase and blind to codes. You need both, which is why every serious system runs both.',
  tech: 'See the table. The one-line interview answer to "why is semantic search not enough": it cannot do exact identifiers, it is weak on numbers and negation, it is blind to jargon coined last week, it cannot filter or aggregate cheaply, and it cannot explain itself.',
  compare: { cols: ['BM25 / lexical', 'Dense vectors', 'Hybrid'],
    rows: [
      ['Matches on', 'the words themselves', 'meaning', 'both, fused by rank'],
      ['Error codes, SKUs, ids', 'excellent', 'poor — all codes look alike', 'excellent'],
      ['Paraphrase and synonyms', 'fails without curated synonyms', 'excellent', 'excellent'],
      ['Negation and numbers', 'literal, so it works', 'weak', 'still weak — use filters'],
      ['New jargon on day one', 'works immediately', 'needs it in training data', 'works'],
      ['Filters and facets', 'first-class, cached', 'bolted on, often slow', 'use the lexical engine'],
      ['Explainability', 'exact score maths', 'an unjustifiable cosine', 'partial'],
      ['Index freshness', 'near real time, ~1s', 'must re-embed', 'limited by the slower lane'],
      ['Cost', 'CPU and disk', 'memory-hungry ANN index', 'both']
    ] },
  trap: 'Hybrid plus a reranker is the production default, and lexical is usually the half that saves you on the queries users complain about.',
  tags: ['hybrid', 'lexical'], orig: 9 },

{ id: 've14', topic: 'vectors', level: 2,
  q: 'How do you choose an embedding model?',
  lay: 'Not by the leaderboard. Build a small labelled set from your own questions and documents, try three or four models, and measure which one actually retrieves your answers.',
  tech: 'Criteria in order: (1) <b>measured recall on YOUR data</b> — leaderboard rank is a weak predictor for a specific domain; (2) <b>languages</b> you must support, tested individually; (3) <b>dimensionality</b> — memory and index cost scale with it, and Matryoshka models let you truncate; (4) <b>max input length</b> versus your chunk size; (5) <b>symmetric or asymmetric</b> — asymmetric models need query/passage prefixes and generally do better on retrieval; (6) <b>hosted or self-hosted</b>, and the cost of re-embedding when you switch; (7) <b>licence</b>.',
  trap: 'The migration cost is the hidden one: changing embedding model means re-embedding the entire corpus and running both indexes in parallel to compare. Budget it before promising a switch.',
  tags: ['embeddings'], orig: 50 },

{ id: 've15', topic: 'vectors', level: 2,
  q: 'What are Matryoshka embeddings?',
  lay: 'A vector where the first hundred numbers are already a decent summary, the first three hundred are better, and the whole thing is best. You can cut it short to save memory and lose only a little accuracy.',
  tech: 'Matryoshka Representation Learning trains so that any prefix of the vector is itself a usable embedding, with information ordered by importance. Practical use: store a truncated 256-dim vector in the hot ANN index for cheap coarse search, keep the full 1536-dim vector on disk, and rerank the top candidates against the full vectors. You get most of the accuracy at a fraction of the memory. text-embedding-3 and several open models support it.',
  trap: 'Truncation must be followed by re-normalisation, and you must truncate queries and documents identically. Mixing a 256-dim query against 1536-dim documents is a dimension error at best and silent nonsense at worst.',
  tags: ['embeddings'], orig: 50 },

{ id: 've16', topic: 'vectors', level: 3,
  q: 'How would you handle filtered vector search efficiently?',
  lay: 'Searching only within "documents from this customer, updated this year" is harder than it sounds, because the fast index is built over everything. There are three strategies and each fails differently.',
  tech: '<ul><li><b>Pre-filtering</b> — restrict the candidate set, then search. Exact results, but a naive implementation degenerates to brute force, and it can break ANN graph connectivity so recall drops.</li><li><b>Post-filtering</b> — ANN search first, then discard non-matching. Fast, but you may end up with far fewer than k results (or none) when the filter is selective, and no error is raised.</li><li><b>Filtered ANN</b> — push the predicate into the index traversal, skipping non-matching nodes during the graph walk or cell scan. This is what modern vector databases implement and it is what you want.</li></ul>Practical guidance: for very selective filters (a small tenant), pre-filter and brute force — it is genuinely faster. For weak filters, filtered ANN. Partitioning the index by the most common filter (one index per tenant) sidesteps the problem entirely at the cost of many small indexes.',
  trap: 'Post-filtering returning fewer than k is the silent failure. Ask for 10, filter down to 2, and answer quality collapses with no error anywhere. Always check what your store actually does.',
  tags: ['ann', 'filtering'], orig: 47 },

{ id: 've17', topic: 'vectors', level: 2,
  q: 'What is a cross-encoder and why can it not be used for first-stage retrieval?',
  lay: 'A cross-encoder reads the question and one document together and judges them properly. That is why it is accurate — and why you cannot run it over ten million documents, because it must be run once per pair.',
  tech: 'A bi-encoder embeds query and document independently, so document vectors are precomputed and search is a similarity lookup. A cross-encoder concatenates them into one input with full cross-attention, which is far more accurate and cannot be precomputed — you would need one forward pass per (query, document) pair. Hence the two-stage architecture: bi-encoder retrieves 50–200 candidates in milliseconds, cross-encoder reranks them in 50–800 ms. Cost scales linearly with candidate count, which is the dial you tune.',
  trap: 'The consequence people miss: a reranker cannot fix recall. If the right chunk was at rank 200 and you passed the top 50, the reranker never sees it. Measure recall@candidates before you spend latency on reranking.',
  tags: ['reranking'], orig: 50 },

{ id: 've18', topic: 'vectors', level: 2,
  q: 'What are sparse embeddings like SPLADE?',
  lay: 'A middle ground: a vector with one entry per vocabulary word, mostly zeros, where the model has decided which extra words this document is also "about" even though they do not appear in it. Word-matching that learned synonyms.',
  tech: 'Learned sparse retrieval. SPLADE produces a sparse vector over the vocabulary with learned term weights and term expansion — so a document about "refunds" gets non-zero weight on "reimbursement" even if that word never appears. It runs on an inverted index, so it inherits lexical search\'s efficiency and exact-match strength while adding semantic expansion. Advantages over dense: interpretable (you can see which terms fired), no separate ANN index, strong on exact terms. Disadvantages: larger indexes than BM25, and an extra model at index and query time.',
  trap: 'Useful framing: SPLADE is often a better single lane than dense-only, and hybrid dense + BM25 remains the pragmatic default because it needs no extra model. Worth naming if asked "what is between BM25 and embeddings".',
  tags: ['splade', 'sparse'], orig: 50 },

{ id: 've19', topic: 'vectors', level: 3,
  q: 'How do you evaluate a retrieval system without human labels?',
  lay: 'Use signals people leave behind — what they clicked, what they did not rephrase, what they escalated. Then bootstrap labels with a model and get a human to check a sample.',
  tech: '<ul><li><b>Implicit feedback</b> — clicks, dwell time, copy actions, absence of a follow-up rephrase. Biased toward what was shown, so correct for position bias if you use it for training.</li><li><b>LLM-generated labels</b> — for each chunk, generate a question it answers; that pair becomes a labelled example. Cheap and surprisingly effective, but it measures your generator unless a human verifies a sample.</li><li><b>Consistency checks</b> — does the answer\'s citation actually contain the claim? A failure implicates retrieval or generation without needing a gold label.</li><li><b>Interleaving</b> — mix two systems\' results and attribute clicks. Needs far less traffic than an A/B to reach significance.</li></ul>Always human-verify a sample; unverified synthetic labels drift toward whatever your generator finds easy.',
  trap: 'The strongest practical answer is "start with 50 hand-labelled questions". It is a day of work, it is unarguable, and it makes every subsequent decision measurable. Elaborate labelless schemes are usually procrastination.',
  tags: ['eval', 'retrieval'], orig: 57 },

{ id: 've20', topic: 'vectors', level: 2,
  q: 'What is the curse of dimensionality and does it affect embeddings?',
  lay: 'In very high-dimensional space, everything ends up roughly the same distance from everything else, so "nearest" stops meaning much. Real embeddings escape this because they do not use the whole space — they live on a much lower-dimensional surface inside it.',
  tech: 'In uniformly-distributed high-dimensional data, the ratio between the nearest and farthest neighbour distances approaches 1, which would make nearest-neighbour search meaningless. Learned embeddings avoid this because they concentrate on a low-dimensional manifold — the intrinsic dimensionality is far below the ambient dimensionality, which is also why ANN indexes work as well as they do. Practical consequences: more dimensions is not automatically better, and beyond a point you pay memory and index cost for no retrieval gain. Measure recall against dimension on your own data.',
  trap: 'A good aside: this is why Matryoshka truncation works at all. If the information were spread uniformly across 1536 dimensions, cutting to 256 would be catastrophic. It is not, because it is concentrated.',
  tags: ['embeddings', 'theory'] },

{ id: 've21', topic: 'vectors', level: 2,
  q: 'How do you handle updates and deletes in a vector index?',
  lay: 'Adding is easy. Deleting is not — most indexes just mark things as gone and skip them, and the space is only reclaimed when you rebuild.',
  tech: 'Inserts: HNSW supports incremental insertion (with some graph-quality degradation over time); IVF assigns to the nearest existing centroid, and centroids drift as the distribution shifts. Deletes: almost always soft — a tombstone that filters results at query time — with space reclaimed only on a merge or rebuild. Updates are a delete plus an insert. Consequences: schedule periodic rebuilds for a churning corpus, monitor the tombstone ratio, and for compliance deletions verify that the document is genuinely unretrievable rather than merely filtered.',
  trap: 'The compliance version of this matters: "deleted" as a query-time filter is not deletion. If you promise erasure, you need a path that removes the vector and the source text and the cache entries, and you need to have tested it.',
  tags: ['ops', 'vector-db'], orig: 34 },

{ id: 've22', topic: 'vectors', level: 3,
  q: 'How would you shard a vector index across machines?',
  lay: 'Split by customer if you can — every query then touches one machine. Otherwise split the documents randomly, ask every machine, and merge the answers.',
  tech: 'Two strategies. <b>Shard by document (scatter-gather)</b>: every query goes to every shard and results are merged. Simple, balanced, but query latency is the slowest shard\'s latency — the tail cost grows with shard count, so hedge or accept partial results after a deadline. <b>Shard by tenant or attribute</b>: each query touches one shard. Far better latency and isolation, but risks hot shards and uneven sizes. Replicate every shard regardless — sharding is for capacity, replication is for availability, and you need both, so your real machine count is the product.',
  trap: 'The tail-latency point is the one interviewers listen for: with 20 shards, your p95 is the p95 of the maximum of 20 samples, which is much worse than any single shard\'s p95. That is why scatter-gather systems hedge.',
  tags: ['scale', 'sharding'], orig: 13 },

{ id: 've23', topic: 'vectors', level: 2,
  q: 'What is normalisation and when must you do it?',
  lay: 'Rescaling every vector to the same length so that only direction matters. Do it once when you store them, and do it to queries too.',
  tech: 'L2 normalisation divides a vector by its magnitude so |v| = 1. After that, dot product equals cosine similarity, which lets you use the faster metric. Must be applied consistently: if documents are normalised and queries are not, the ranking is still correct for cosine but wrong for dot product, and the scores are meaningless. Some models output normalised vectors already — check rather than assume. Some vector databases normalise on ingest depending on the configured metric; know which.',
  trap: 'A subtle bug: normalising after truncating a Matryoshka embedding is required, and normalising before truncation gives a vector that is no longer unit length. Order matters.',
  tags: ['embeddings', 'similarity'], orig: 19 },

{ id: 've24', topic: 'vectors', level: 2,
  q: 'What is MMR (maximal marginal relevance) and when do you want it?',
  lay: 'Stop the top five results all being the same paragraph said five ways. MMR picks results that are relevant AND different from what you have already picked.',
  tech: 'Greedy selection maximising <span class="mono">λ·sim(q, d) − (1−λ)·max_{d\'∈S} sim(d, d\')</span> — relevance to the query minus similarity to what is already selected. λ near 1 is pure relevance; lower values buy diversity. Useful when your corpus has heavy near-duplication (versioned documents, boilerplate, chunk overlap), where the top k are otherwise redundant and waste context budget.',
  trap: 'The alternative that is often better: deduplicate first. If your top five are near-identical because of chunk overlap, fix the overlap or deduplicate by content hash rather than adding a diversity parameter to tune.',
  tags: ['mmr', 'retrieval'] },

{ id: 've25', topic: 'vectors', level: 2,
  q: 'What is the difference between an embedding model and a reranker model?',
  lay: 'The embedding model has to describe every document in advance without knowing the question. The reranker gets to read the question and the document together. That is why one is fast and one is accurate.',
  tech: 'Embedding model (bi-encoder): produces a fixed vector per text independently, so documents are embedded once at index time and search is a vector lookup. Reranker (cross-encoder): takes the pair as one input and outputs a relevance score, so it must run per pair at query time. Their training differs too — embedders are trained with contrastive objectives over large batches; rerankers are trained as binary or graded relevance classifiers on (query, passage) pairs.',
  trap: 'They are complementary, not competing, and using the same model for both is a category error. If someone proposes "just use the reranker for retrieval", ask how they plan to run ten million forward passes per query.',
  tags: ['reranking', 'embeddings'], orig: 50 },

{ id: 've26', topic: 'vectors', level: 3,
  q: 'How do you monitor a vector index in production?',
  lay: 'Watch how long searches take, how many results come back, whether the index is keeping up with new documents, and whether search quality has quietly drifted.',
  tech: '<ul><li><b>Latency</b> p50/p95/p99 per stage — embed, search, filter, rerank.</li><li><b>Recall drift</b> — run a fixed probe set against exact search weekly and alarm if ANN recall drops.</li><li><b>Result count distribution</b> — a spike in queries returning fewer than k means a filter or post-filtering problem.</li><li><b>Index freshness lag</b> — time from source change to retrievable.</li><li><b>Size and tombstone ratio</b> — when tombstones exceed a threshold, schedule a rebuild.</li><li><b>Score distribution</b> — a shift in the mean top-1 score usually means the embedding model, the corpus or the query mix changed.</li><li><b>Empty-retrieval rate</b> — the leading indicator of a corpus gap.</li></ul>',
  trap: 'Score distribution drift is the underrated one. It moves before user complaints do, and it catches silent changes — a re-embedding job that used the wrong model, a corpus import that doubled the document count.',
  tags: ['observability', 'ops'], orig: 39 },

{ id: 've27', topic: 'vectors', level: 2,
  q: 'What is a two-tower model?',
  lay: 'Two encoders trained together — one for questions, one for documents — so that matching pairs end up close. It is the standard shape behind retrieval and recommendation.',
  tech: 'Separate encoders for query and item, trained jointly with a contrastive loss so relevant pairs have high similarity. The point is that the item tower can be run offline over the whole catalogue and its outputs indexed, while the query tower runs at request time. Widely used in recommenders (user tower, item tower) and in retrieval (query tower, passage tower). Asymmetric embedding models with query/passage prefixes are effectively a two-tower model sharing weights.',
  trap: 'The training detail that matters: in-batch negatives make training cheap but easy, and adding HARD negatives — items the current model ranks highly and should not — is where most of the quality gain comes from.',
  tags: ['embeddings', 'training'] },

{ id: 've28', topic: 'vectors', level: 2,
  q: 'How does semantic caching use vector search, and what is different about it?',
  lay: 'It is a vector index of questions you have already answered. Different from document retrieval in one important way: getting it slightly wrong does not mean a worse result, it means a wrong answer served instantly.',
  tech: 'Index the embeddings of previously-answered questions; on a new question, search and reuse the stored answer above a threshold. Differences from document retrieval: k = 1 (you are looking for equivalence, not relevance); the threshold is a precision decision with a direct customer cost; the key must include tenant, locale, prompt version, model version and retrieved-content version; and it needs a TTL by intent class. Tune the threshold against LABELLED paraphrase pairs, not by guessing a number that sounds high.',
  trap: 'Negation is the canonical failure: "is X refundable" and "is X not refundable" are extremely close in embedding space, and one of them gets the other\'s answer. Any semantic cache demo that does not test negation has not been tested.',
  tags: ['caching', 'semantic-cache'], orig: 1 },

{ id: 've29', topic: 'vectors', level: 2,
  q: 'What is recall@k, MRR and nDCG — and when do you use each?',
  lay: 'Recall asks "was the right thing anywhere in the top ten?". MRR asks "how high was the first right thing?". nDCG asks "how good was the whole ordering, given that some results are more relevant than others?".',
  tech: '<ul><li><b>recall@k</b> — fraction of queries where at least one relevant document is in the top k. The right first metric for RAG, because the generator only sees k.</li><li><b>MRR</b> — mean of 1/rank of the first relevant result. Good when there is one right answer and its position matters.</li><li><b>nDCG@k</b> — discounted cumulative gain normalised by the ideal ordering. Handles graded relevance (very relevant, somewhat, not) and rewards putting the best first. The right metric for search-style ranking.</li><li><b>MAP</b> — mean average precision, when there are several relevant documents per query and you care about all of them.</li></ul>',
  trap: 'For RAG specifically, report recall@k at the k you actually pass to the model, plus context precision. A high nDCG with poor recall@5 tells you the ordering is good and the model is not getting the answer.',
  tags: ['metrics', 'eval'], orig: 17 },

{ id: 've30', topic: 'vectors', level: 3,
  q: 'You have 1.2 billion vectors and 64 GB of RAM per node. What decides your index?',
  lay: 'Memory, long before anything else. The raw vectors will not fit, so the question becomes how much you can compress them and still find the right answers.',
  tech: 'Arithmetic first: 1.2B × 768 × 4 bytes ≈ 3.4 TB of raw float32. That is the binding constraint, not query latency and not recall. Path: <ol><li><b>Compress</b> — product quantisation at ~96 bytes/vector brings it to ~115 GB; scalar quantisation to int8 gives ~880 GB, still too much.</li><li><b>Shard</b> — at ~115 GB compressed you need at least two nodes for the index alone, more with replicas and headroom.</li><li><b>Rerank against exact vectors</b> stored on disk for the top few hundred, recovering the recall PQ cost you.</li><li><b>Filter hard first</b> — at this scale, metadata filtering by tenant or recency is what makes queries tractable.</li></ol>',
  trap: 'The reflex to have: quote the raw memory figure out loud before discussing algorithms. At billion scale the index choice falls out of the arithmetic, and candidates who start with "I would use HNSW" without computing 3.4 TB have not understood the constraint.',
  tags: ['scale', 'pq'], orig: 13 },

{ id: 've31', topic: 'vectors', level: 2,
  q: 'What is the difference between semantic similarity and relevance?',
  lay: 'Two texts can be about the same topic and still not answer each other. "How do I cancel my subscription" and "why did my subscription renew" are extremely similar and want completely different answers.',
  tech: 'Embedding similarity measures topical and lexical proximity in the model\'s learned space. Relevance is task-specific: does this passage answer this question. They correlate and are not the same, which is precisely why cross-encoder reranking helps so much — it is trained on relevance directly rather than on similarity. It is also why negation and intent distinctions survive similarity: the vectors are close because the topic is the same.',
  trap: 'This gap is the theoretical justification for the whole retrieve-then-rerank architecture. If similarity equalled relevance, one stage would be enough.',
  tags: ['retrieval', 'theory'], orig: 9 },

{ id: 've32', topic: 'vectors', level: 2,
  q: 'How do you search over images or audio alongside text?',
  lay: 'Put both kinds of thing into the same space, so a picture of a dog and the word "dog" land near each other. Or describe the picture in words first and search the words.',
  tech: 'Two approaches: <ul><li><b>Joint embedding</b> — a model like CLIP trained with a contrastive objective across modalities places images and text in one space, so text queries retrieve images directly. Best for visual similarity; weaker on fine-grained text inside images.</li><li><b>Caption-then-embed</b> — a vision model describes the image at index time, and you embed and search the caption. Cheap, searchable with your existing text stack, works well for documents and screenshots, and loses purely visual detail.</li></ul>Most production systems do both and fuse the rankings, because they fail differently.',
  trap: 'For document images and screenshots, an OCR pass feeding text retrieval usually beats a joint embedding, because the information is text that happens to be rendered as pixels. Choose based on whether the signal is visual or textual.',
  tags: ['multimodal', 'retrieval'] }

]);
