/* ============================================================
   Multiple-choice bank for the quiz mode.
   Every wrong option is a real misconception, not filler —
   the explanation says why the tempting answer is wrong.
   { topic, q, o: [...], a: index, e: explanation }
   ============================================================ */
window.MCQ = (window.MCQ || []).concat([

/* ---------------- foundations ---------------- */
{ topic: 'foundations', q: 'Roughly how many English words fit in 1,000 tokens?', o: ['about 250', 'about 750', 'about 1,000', 'about 4,000'], a: 1,
  e: 'About 0.75 words per token for English, or 4 characters per token. Code and non-Latin scripts cost considerably more tokens per unit of meaning.' },
{ topic: 'foundations', q: 'Why can a model struggle to count the letters in "strawberry"?', o: ['It cannot count', 'It sees tokens, not characters', 'Counting is disabled for safety', 'It needs a larger context window'], a: 1,
  e: 'The tokenizer destroys character-level structure before the model sees anything. It receives two or three chunks, not ten letters.' },
{ topic: 'foundations', q: 'Which is NOT a reason to prefer subword tokenisation?', o: ['No unknown-word token is ever needed', 'A fixed, manageable vocabulary size', 'It makes attention linear in sequence length', 'Rare words decompose into reusable pieces'], a: 2,
  e: 'Attention is quadratic regardless of tokenisation. Subwords shorten sequences relative to characters, which helps, but they do not change the complexity class.' },
{ topic: 'foundations', q: 'Temperature 0 gives you...', o: ['Perfectly deterministic output, byte for byte, on every provider', 'Greedy decoding, which is usually but not always reproducible', 'The most creative and varied output the model can produce', 'An error, because 0 is not a legal temperature on most APIs'], a: 1,
  e: 'Greedy means always take the argmax. Batching, GPU non-determinism and MoE routing can still change the token, so pin a seed too and assert on parsed fields rather than exact strings.' },
{ topic: 'foundations', q: 'Top-p 0.9 means...', o: ['Keep the top 90 tokens', 'Keep the smallest set of tokens whose probabilities sum to 0.9', 'Multiply logits by 0.9', 'Keep tokens with probability above 0.9'], a: 1,
  e: 'A cut by cumulative mass, not by rank or by threshold. The survivor set shrinks when the model is confident and grows when it is not, which is the whole argument for nucleus over top-k.' },
{ topic: 'foundations', q: 'Which setting most reliably breaks JSON output?', o: ['temperature 0', 'top_p 1.0', 'a repetition penalty of 1.2', 'a stop sequence'], a: 2,
  e: 'JSON repeats braces, quotes and key names by design, and a repetition penalty punishes exactly those tokens. Use constrained decoding instead.' },
{ topic: 'foundations', q: 'max_tokens does what?', o: ['Makes the model concise', 'Truncates generation at a hard limit', 'Sets the context window', 'Controls randomness'], a: 1,
  e: 'It is a guillotine, not an editor. Ask for brevity in the prompt and keep max_tokens as the circuit breaker against runaway generation.' },
{ topic: 'foundations', q: 'What is a stop sequence most critically used for in an agent?', o: ['Reducing cost by cutting generation short', 'Preventing the model hallucinating its own tool results', 'Improving accuracy by constraining the output format', 'Enabling the response to be streamed to the client'], a: 1,
  e: 'Stopping at "Observation:" forces your code to supply the real tool result. Without it the model happily writes a plausible fake one and continues.' },
{ topic: 'foundations', q: 'Mixture-of-experts models are cheap to run and expensive to...', o: ['train', 'host in memory', 'quantise', 'evaluate'], a: 1,
  e: 'Every expert must be resident even though only a couple compute per token. Mixtral 8x7B is ~46.7B parameters of memory and ~12.9B of compute per token.' },
{ topic: 'foundations', q: 'Chinchilla scaling showed that models of that era were...', o: ['too small', 'undertrained on data', 'over-regularised', 'trained at too high a learning rate'], a: 1,
  e: 'Compute-optimal is roughly 20 training tokens per parameter. That result shifted the field toward smaller models trained far longer.' },
{ topic: 'foundations', q: 'Which knowledge should be non-parametric (retrieved) rather than in the weights?', o: ['Grammar and general language competence', 'Anything that changes, must be cited, or is permission-scoped', 'Multi-step reasoning and arithmetic ability', 'House style and output formatting conventions'], a: 1,
  e: 'Weights cannot be versioned, cited, permission-scoped or deleted. Anything with those requirements belongs in an index.' },
{ topic: 'foundations', q: 'The softmax probability of the first token of a fabricated citation is typically...', o: ['very low, which is how you detect it', 'high — confidence is uncorrelated with correctness', 'exactly 0.5', 'unavailable from any API'], a: 1,
  e: 'Calibration is for next-token prediction, not factual truth. Confident fabrication is exactly the case where confidence-based detection fails.' },
{ topic: 'foundations', q: 'When should you NOT use an LLM?', o: ['When the input is messy natural language', 'When the task is a deterministic lookup or a rule', 'When you need summarisation', 'When output is open-ended'], a: 1,
  e: 'If the answer is a lookup, look it up. If it is arithmetic, calculate it. Tabular prediction still belongs to gradient-boosted trees.' },
{ topic: 'foundations', q: 'A base model differs from an instruct model because it...', o: ['is smaller', 'has only been trained to continue text, not to answer', 'has no tokenizer', 'cannot be fine-tuned'], a: 1,
  e: 'A base model will continue your question with more questions. Instruction tuning is what makes it answer.' },
{ topic: 'foundations', q: 'What does the chat template do, and why does using the wrong one matter?', o: ['Nothing functional; it only affects how the transcript is displayed', 'It inserts the model-specific role delimiters, and a mismatch degrades quality', 'It compresses the conversation so more turns fit in the window', 'It is what allows the response to be streamed token by token'], a: 1,
  e: 'Models are trained with specific delimiters. Hand-rolling "User: ... Assistant:" for a model trained on different tokens costs real accuracy and produces no error.' },

/* ---------------- transformers ---------------- */
{ topic: 'transformers', q: 'Which sublayer holds most of a transformer block\'s parameters?', o: ['self-attention', 'the feed-forward network', 'LayerNorm', 'the positional encoding'], a: 1,
  e: 'Roughly two thirds sit in the feed-forward, and that is where factual associations live. Attention is routing, not knowledge.' },
{ topic: 'transformers', q: 'Which step is the only one where information moves BETWEEN token positions?', o: ['LayerNorm', 'the residual add', 'the attention-weighted sum of values', 'the GELU non-linearity'], a: 2,
  e: 'Everything else — LayerNorm, the feed-forward, the residual — runs on each position independently.' },
{ topic: 'transformers', q: 'The causal mask works by...', o: ['dropping future tokens from the input', 'setting attention scores to future positions to minus infinity', 'reversing the sequence', 'limiting the context window'], a: 1,
  e: 'Minus infinity becomes exactly zero after softmax. That is what makes it a language model rather than an encoder, and it is what makes the KV cache valid.' },
{ topic: 'transformers', q: 'Why divide attention scores by the square root of d_k?', o: ['to normalise the output', 'to keep the variance stable so softmax does not saturate', 'to save compute', 'to enable multi-head attention'], a: 1,
  e: 'The dot product of two d-dimensional vectors has variance proportional to d. Without scaling, softmax becomes nearly one-hot and gradients vanish.' },
{ topic: 'transformers', q: 'More attention heads is the same as more layers.', o: ['True: both add capacity in the same way', 'False: heads are parallel sub-questions, layers are serial depth', 'True for encoder models, false for decoder-only ones', 'True above 32 heads, where they begin to specialise'], a: 1,
  e: 'Different axes. Heads split one attention step into parallel questions at the same depth; layers stack blocks so later ones read earlier output.' },
{ topic: 'transformers', q: 'Grouped-query attention exists primarily to...', o: ['improve accuracy', 'shrink the KV cache so batch sizes can be larger', 'speed up training', 'reduce the parameter count'], a: 1,
  e: 'Llama-3 70B has 64 query heads and 8 KV heads — an 8x KV cache reduction. Smaller cache means bigger batch, which means better GPU utilisation and lower cost per token.' },
{ topic: 'transformers', q: 'FlashAttention is...', o: ['an approximation of attention', 'an exact, IO-aware reimplementation', 'a form of sparse attention', 'a quantisation method'], a: 1,
  e: 'It never materialises the n-by-n score matrix in slow memory, using online softmax over tiles. The output is numerically equivalent — it changes memory access, not mathematics.' },
{ topic: 'transformers', q: 'RoPE encodes position by...', o: ['adding a fixed position vector to the input embeddings', 'rotating Q and K by an angle proportional to position, every layer', 'concatenating a position index onto each token embedding', 'masking tokens beyond a fixed distance from the current one'], a: 1,
  e: 'The rotation makes the dot product depend on relative offset, which is what attention actually needs — and it gives you a knob for context extension after training.' },
{ topic: 'transformers', q: 'The residual stream is best described as...', o: ['a gradient-flow trick with no conceptual meaning', 'a running document each block reads, edits and adds back to', 'the output of the attention sublayer before projection', 'the final hidden layer before the vocabulary projection'], a: 1,
  e: 'Nothing is overwritten; each sublayer contributes an additive update. That is why deleting a middle layer of a large model often barely changes behaviour.' },
{ topic: 'transformers', q: 'Prefill is bound by ____ and decode is bound by ____.', o: ['memory / compute', 'compute / memory bandwidth', 'network / disk', 'both are compute-bound'], a: 1,
  e: 'Prefill does big matrix-matrix products; decode reads all the weights to produce one token. That asymmetry explains batching, speculative decoding and quantisation gains.' },
{ topic: 'transformers', q: 'Which does the KV cache NOT speed up?', o: ['decode', 'prefill', 'long generations', 'multi-turn conversations'], a: 1,
  e: 'Nothing is cached on the first pass over the prompt. Prefill is what prompt (prefix) caching addresses, and they are different mechanisms.' },
{ topic: 'transformers', q: 'Speculative decoding at a 0% acceptance rate is...', o: ['neutral', 'a net slowdown', 'still a 2x speedup', 'mathematically impossible'], a: 1,
  e: 'You pay for every draft token and accept none. Expected accepted tokens is (1 - a^(g+1))/(1 - a); at a = 0 it is 1, while you still paid for g drafts.' },
{ topic: 'transformers', q: 'Speculative decoding changes the output distribution.', o: ['True', 'False — modified rejection sampling preserves it exactly', 'True at high temperature', 'Only for MoE models'], a: 1,
  e: 'The acceptance rule is constructed so the final distribution matches the target model. You get the same answer, faster.' },
{ topic: 'transformers', q: 'Lost in the middle means accuracy is worst when the answer sits...', o: ['at the start', 'in the middle of a long context', 'at the end', 'in a system prompt'], a: 1,
  e: 'The curve is U-shaped by position and the sag deepens with length. Rerank so the best chunk is first, and restate the task at the very end.' },
{ topic: 'transformers', q: 'Attention sinks matter because...', o: ['they measurably improve accuracy on long-context retrieval', 'evicting the first few tokens in a sliding window collapses quality', 'they let the KV cache be stored in far less memory', 'they are what makes rotary position embedding possible'], a: 1,
  e: 'Softmax must put its mass somewhere, and heads dump spare attention on the first tokens. Keep about four of them permanently when you implement KV eviction.' },
{ topic: 'transformers', q: 'PagedAttention is analogous to which operating-system idea?', o: ['garbage collection', 'virtual memory paging', 'process scheduling', 'copy-on-write forking only'], a: 1,
  e: 'Fixed-size KV blocks with a block table, so waste is bounded by a block instead of by max_tokens. Block sharing with copy-on-write gives prefix caching for free.' },

/* ---------------- training ---------------- */
{ topic: 'training', q: 'Which stage gives a model most of its knowledge?', o: ['SFT', 'pretraining', 'RLHF', 'prompt engineering'], a: 1,
  e: 'Pretraining on trillions of tokens. SFT and preference tuning shape behaviour far more than they add knowledge.' },
{ topic: 'training', q: 'The single practical difference between LoRA and QLoRA is that QLoRA...', o: ['trains a larger number of adapter parameters', 'quantises the frozen base to 4-bit so it fits in far less VRAM', 'replaces the adapters with a quantisation-aware update', 'is designed for vision models rather than language models'], a: 1,
  e: 'Same algorithm, same adapters. QLoRA is the memory trick on the frozen part, and it is why a 70B model can be tuned on one 80GB card.' },
{ topic: 'training', q: 'In LoRA, which matrices are trained?', o: ['all of W', 'only the low-rank A and B beside the frozen W', 'only the embeddings', 'only the LayerNorm scales'], a: 1,
  e: 'W stays frozen; you train A (r x d) and B (d x r). At r=16 on an 8B model that is roughly 0.1% of the parameters.' },
{ topic: 'training', q: 'LoRA adapters at inference...', o: ['always add latency', 'can be merged into the base for zero added latency', 'require a separate GPU', 'must be re-trained per request'], a: 1,
  e: 'Merge BA into W and you have an ordinary model. Keep them separate only when you want to hot-swap per tenant.' },
{ topic: 'training', q: 'DPO replaced RLHF for most teams because it...', o: ['is more accurate', 'needs no reward model and no PPO loop', 'requires less data', 'works on base models'], a: 1,
  e: 'Two models in memory instead of four, offline training instead of online rollouts, and far more stable — for most of the benefit.' },
{ topic: 'training', q: 'GRPO removes which component of PPO?', o: ['the reference model', 'the value/critic network', 'the KL penalty', 'the reward function'], a: 1,
  e: 'The group mean serves as the baseline for advantage estimation, so no critic is needed. You pay in inference: G rollouts per prompt.' },
{ topic: 'training', q: 'GRPO is the right choice when...', o: ['you have no data', 'a program can automatically score an answer right or wrong', 'you need the smallest model', 'you only have preference pairs'], a: 1,
  e: 'It lives or dies on a verifiable reward — maths answers, passing tests, parseable output. With only human preferences, use DPO.' },
{ topic: 'training', q: 'Your model has the right facts but the wrong tone and format. Reach for...', o: ['better retrieval', 'a LoRA fine-tune or preference tuning', 'a bigger context window', 'a different vector database'], a: 1,
  e: 'Fine-tuning teaches form; RAG supplies facts. Wrong format is a form problem.' },
{ topic: 'training', q: 'Fine-tuning a model on your documentation so it "knows" it is...', o: ['the standard approach', 'an expensive way to build a bad search engine', 'required for domain accuracy', 'cheaper than RAG'], a: 1,
  e: 'No citations, no versioning, no deletion, and it must be redone whenever the documents change. Retrieve instead.' },
{ topic: 'training', q: 'Catastrophic forgetting is best prevented by...', o: ['training for more epochs so the model consolidates', 'PEFT, low learning rates, few epochs and mixed-in general data', 'using a much larger batch size to smooth the updates', 'adding layers so there is capacity for the new task'], a: 1,
  e: 'And by evaluating on a general regression suite, not just your task metric — otherwise you will not notice.' },
{ topic: 'training', q: 'Roughly how many examples do you need for a LoRA that changes format and style?', o: ['5-10', '100-500', '50,000+', '1 million'], a: 1,
  e: 'Format and style are cheap to teach. Data quality dominates quantity — the LIMA result showed 1,000 curated examples going a very long way.' },
{ topic: 'training', q: 'Full fine-tuning a 7B model needs roughly how much VRAM (fp16 + Adam)?', o: ['14 GB', 'over 100 GB', '35 GB', '8 GB'], a: 1,
  e: 'About 16 bytes per parameter: 2 for weights, 2 for gradients, 8 for two fp32 Adam moments, plus activations. That is why LoRA exists.' },
{ topic: 'training', q: 'Distillation is primarily a...', o: ['quality project', 'cost and latency project', 'safety project', 'data collection project'], a: 1,
  e: 'A student never exceeds its teacher and inherits its mistakes. Reach for it when the pipeline works and needs to be cheaper.' },
{ topic: 'training', q: 'When fine-tuning, the loss should be computed over...', o: ['the whole sequence including the prompt', 'the assistant response tokens only', 'the system prompt only', 'a random subset'], a: 1,
  e: 'Otherwise you train the model to generate the user\'s turn as well, which quietly degrades everything. Mask the prompt.' },
{ topic: 'training', q: 'A reward model in RLHF characteristically learns to prefer...', o: ['shorter answers', 'longer answers', 'answers with citations', 'answers in JSON'], a: 1,
  e: 'Length bias is well documented and is why early RLHF models became verbose. Length-normalise the reward or you optimise for word count.' },

/* ---------------- inference ---------------- */
{ topic: 'inference', q: 'Streaming improves...', o: ['total latency', 'perceived latency after the first token', 'time to first token', 'cost'], a: 1,
  e: 'Total time and cost are identical, and TTFT is unchanged. Streaming affects everything after the first token.' },
{ topic: 'inference', q: 'Which most reliably reduces time to first token?', o: ['streaming', 'prompt caching a stable prefix', 'a larger batch size', 'a repetition penalty'], a: 1,
  e: 'A cache hit skips prefill entirely. Bigger batches usually make TTFT worse, not better.' },
{ topic: 'inference', q: 'Prompt caching breaks when...', o: ['the answer is long', 'anything near the TOP of the prompt changes', 'temperature changes', 'you use tools'], a: 1,
  e: 'It is a prefix cache. A timestamp, request id or shuffled tool list near the top zeroes your hit rate and doubles your input bill.' },
{ topic: 'inference', q: 'Continuous batching means...', o: ['it simply uses much larger batches than static batching', 'finished sequences are evicted and new ones admitted every decode step', 'it batches the prompts together and decodes them as one sequence', 'it moves the decode phase onto CPU to free the GPU'], a: 1,
  e: 'Static batching lets one long generation hold seven short ones hostage. In-flight batching is the scheduling half of a modern inference server.' },
{ topic: 'inference', q: 'Which usually limits your batch size in production?', o: ['model weights', 'KV cache memory', 'network bandwidth', 'tokenizer speed'], a: 1,
  e: 'Weights are a fixed cost; the KV cache scales with sequence length and batch. That is why GQA, PagedAttention and KV quantisation matter so much.' },
{ topic: 'inference', q: 'int4 quantisation of a 70B model gives roughly what weight size?', o: ['141 GB', '35 GB', '70 GB', '9 GB'], a: 1,
  e: '70.6e9 x 0.5 bytes is about 35 GB, which is what makes one 80GB card viable with room for the KV cache.' },
{ topic: 'inference', q: 'KV cache quantisation buys you...', o: ['a smaller model', 'a larger batch size', 'faster prefill', 'better accuracy'], a: 1,
  e: 'It shrinks per-request memory, not the model. Weight quantisation shrinks the model; they are different axes and they compose.' },
{ topic: 'inference', q: 'A cascade routes...', o: ['every request to the biggest model', 'a small model first and escalates on a confidence check', 'randomly between models', 'by user id'], a: 1,
  e: 'The escalation signal is the hard part. Prefer verifiable checks — did it parse, does the citation exist — over self-reported confidence.' },
{ topic: 'inference', q: 'The correct first response to an LLM timeout is...', o: ['retry three times immediately with the same prompt', 'retry once with backoff and jitter, then fail over and mark it degraded', 'raise the client timeout to 120 seconds and wait it out', 'return an error page and let the user try again later'], a: 1,
  e: 'Tight retries multiply load on a struggling service. And a degraded answer must never be written to the cache.' },
{ topic: 'inference', q: 'On a 429, which detail do engineers most often get wrong?', o: ['retrying at all, rather than failing the request', 'using backoff without FULL jitter, so clients retry in lockstep', 'reading the response body before deciding what to do', 'logging the 429 rather than treating it as an error'], a: 1,
  e: 'Partial jitter still synchronises the herd. Also respect Retry-After and throttle at source with a token bucket sized to your quota.' },
{ topic: 'inference', q: 'Request hedging costs roughly...', o: ['double', 'about 5% more calls', 'nothing', '10x'], a: 1,
  e: 'Fire the duplicate after p95 elapses. Never hedge a non-idempotent operation — you will send two emails.' },
{ topic: 'inference', q: 'Output tokens typically cost how much relative to input tokens?', o: ['the same', '3-5x more', 'half', '100x more'], a: 1,
  e: 'Which is why capping output length and asking for brevity is one of the cheapest cost levers available.' },
{ topic: 'inference', q: 'In a stateless chat API, total cost across n turns grows...', o: ['linearly', 'quadratically', 'logarithmically', 'not at all'], a: 1,
  e: 'Turn 30 sends everything from turns 1-29. Prompt caching flattens most of this curve, which is why it matters so much in long conversations.' },
{ topic: 'inference', q: 'Cache penetration is...', o: ['an attacker reading cached data', 'requests for keys absent from both cache and store', 'the cache filling up', 'two writers racing'], a: 1,
  e: 'There is nothing to cache, so every request falls through. Negative caching with a short TTL, a Bloom filter, and rate limiting on MISS rate.' },
{ topic: 'inference', q: 'A cache stampede is fixed by...', o: ['putting a Bloom filter in front of the backing store', 'single-flight regeneration, serve-stale-while-revalidate, TTL jitter', 'allocating a larger cache so entries survive longer', 'disabling the cache for the affected key entirely'], a: 1,
  e: 'A Bloom filter addresses penetration, which is a different failure. A stampede is one hot key expiring under concurrent load.' },
{ topic: 'inference', q: 'The most dangerous property of a semantic cache is that it...', o: ['is slow', 'can serve a confidently WRONG answer', 'costs too much', 'cannot be invalidated'], a: 1,
  e: 'Negation is the classic case: "is X refundable" and "is X not refundable" embed very closely. Tune the threshold against labelled paraphrases.' },

/* ---------------- prompting ---------------- */
{ topic: 'prompting', q: 'Where should the current task sit in a very long prompt?', o: ['at the very top only', 'restated at the END', 'in the middle', 'in the tool descriptions'], a: 1,
  e: 'Attention is weakest in the middle of a long context. Restating the task each turn costs a few hundred tokens and is the cheapest reliability fix there is.' },
{ topic: 'prompting', q: 'What belongs at the TOP of the prompt for caching purposes?', o: ['the user question', 'stable content: system prompt', 'a timestamp', 'retrieved chunks that change per turn'], a: 1,
  e: 'A prefix cache only helps if the prefix is byte-identical. Everything volatile goes at the bottom.' },
{ topic: 'prompting', q: 'Adding few-shot examples to a strong model...', o: ['always helps', 'can hurt by over-constraining the output', 'is required', 'reduces cost'], a: 1,
  e: 'On capable models, explicit format specification often beats examples. If quality drops after adding examples, remove them.' },
{ topic: 'prompting', q: 'The most valuable few-shot examples are...', o: ['the most typical cases', 'the awkward edge cases, including refusals', 'the shortest ones', 'randomly sampled'], a: 1,
  e: 'Examples of easy cases teach nothing. A refusal example is often the highest-value one in the block.' },
{ topic: 'prompting', q: 'Chain of thought helps because...', o: ['the instruction makes the model apply more effort per token', 'each generated token is another forward pass, adding serial computation', 'the reasoning text pulls more relevant context into the window', 'writing out steps implicitly lowers the sampling temperature'], a: 1,
  e: 'A fixed-depth network cannot do six serial steps in one pass. Written reasoning is literally the scratchpad, extended in time.' },
{ topic: 'prompting', q: 'Self-consistency requires...', o: ['temperature 0, so each sample is the model\'s best answer', 'a temperature above 0, or every sample is identical', 'a reward model to score the sampled reasoning paths', 'a fine-tune that teaches the model to vary its reasoning'], a: 1,
  e: 'Sample n=3-5 at around 0.7-0.8 and take the majority. It costs n times as much, so gate it on low confidence.' },
{ topic: 'prompting', q: 'The most reliable way to get valid JSON is...', o: ['asking politely in the prompt', 'constrained decoding against a schema', 'lowering temperature', 'retrying until it parses'], a: 1,
  e: 'Constrained decoding masks invalid tokens so the output is valid by construction. Note that valid is not the same as correct.' },
{ topic: 'prompting', q: 'A rolling summary should always be generated from...', o: ['the previous summary', 'the ORIGINAL transcript', 'the last turn only', 'the system prompt'], a: 1,
  e: 'Summarising a summary loses specifics each pass, until "refund order 4471 for $89.20" becomes "the customer had a billing issue".' },
{ topic: 'prompting', q: 'Which memory layer holds "the user prefers metric units"?', o: ['working memory', 'semantic (long-term) memory', 'episodic memory', 'the KV cache'], a: 1,
  e: 'Durable facts and preferences are semantic memory. Episodic memory holds specific past events and their outcomes.' },
{ topic: 'prompting', q: 'The hardest part of agent memory is...', o: ['storage', 'reconciliation', 'embedding', 'retrieval'], a: 1,
  e: 'Without it you accumulate "lives in Berlin" and "lives in Munich" side by side and retrieve whichever is nearer the query.' },
{ topic: 'prompting', q: 'The system prompt is...', o: ['a security boundary', 'a strong prior that can be argued with', 'immutable', 'invisible to the model'], a: 1,
  e: 'Anything that must be enforced — tenant filtering, spend limits, which tools exist — is enforced in code outside the model.' },
{ topic: 'prompting', q: 'Prompt compression is usually unnecessary when...', o: ['the prompt is long', 'the large block is a stable prefix that can be cached', 'you use tools', 'the model is small'], a: 1,
  e: 'Caching gives you roughly a 90% discount for free. Compression pays where content is large AND changes per request.' },
{ topic: 'prompting', q: 'To make a model reliably say "I do not know", the highest-value change is...', o: ['a longer and firmer refusal instruction in the prompt', 'detecting empty retrieval in code and not calling the model', 'lowering the temperature so it commits to fewer guesses', 'adding more refusal examples to the few-shot block'], a: 1,
  e: 'With no context the model answers from parametric memory and sounds certain. That one branch removes more hallucination than any wording.' },
{ topic: 'prompting', q: 'Dynamic few-shot (retrieved examples) has which hidden cost?', o: ['worse accuracy', 'it breaks prefix caching for the example block', 'it needs fine-tuning', 'it requires a GPU'], a: 1,
  e: 'The examples change per request, so they are fresh input tokens every time. Place them after any cached prefix and measure whether the accuracy gain is worth it.' },
{ topic: 'prompting', q: 'Tool descriptions are best thought of as...', o: ['documentation', 'prompts', 'type annotations', 'comments'], a: 1,
  e: 'Most tool-selection failures are description failures. Rewriting one description often beats changing model.' },

/* ---------------- rag ---------------- */
{ topic: 'rag', q: 'Semantic search alone fails hardest on...', o: ['paraphrased questions', 'exact identifiers like error codes and SKUs', 'long documents', 'multi-turn conversations'], a: 1,
  e: 'Identifiers carry almost no semantic signal, so every code embeds into roughly the same region. BM25 finds them trivially.' },
{ topic: 'rag', q: 'Reciprocal rank fusion is the default for hybrid search because it...', o: ['is fastest', 'uses only ranks', 'is most accurate', 'requires no tuning of k'], a: 1,
  e: 'Cosine and BM25 scores live on incomparable scales that also shift as the corpus grows. Rank-based fusion is invariant to both.' },
{ topic: 'rag', q: 'A reranker cannot fix...', o: ['ordering', 'recall — it never sees what retrieval missed', 'latency', 'chunk size'], a: 1,
  e: 'If the answering chunk was at rank 200 and you passed the top 50, re-sorting does nothing. Measure recall@candidates first.' },
{ topic: 'rag', q: 'Parent-child retrieval means you...', o: ['index large chunks for recall and return small excerpts', 'index small children for precision and return the large parent', 'use one embedding model for children and another for parents', 'chunk the document twice with two different overlap settings'], a: 1,
  e: 'It resolves the core tension: small chunks retrieve better, big chunks answer better. Remember to deduplicate by parent id.' },
{ topic: 'rag', q: 'Contextual retrieval works by...', o: ['retrieving more chunks and letting the model sort it out', 'prepending an LLM-written sentence situating each chunk in its document', 'running the reranker twice with different candidate sets', 'increasing the overlap between adjacent chunks'], a: 1,
  e: 'One cheap call per chunk at index time. Anthropic reported roughly a 35% drop in retrieval failures, and around 49% combined with BM25.' },
{ topic: 'rag', q: 'Which chunking strategy respects meaning rather than punctuation?', o: ['fixed-size', 'recursive', 'semantic (embedding-distance cuts)', 'fixed with overlap'], a: 2,
  e: 'Semantic chunking cuts where consecutive sentences diverge in embedding space. It costs an embedding per sentence at index time.' },
{ topic: 'rag', q: 'The safest default chunking strategy on day one is...', o: ['semantic', 'recursive with 10-20% overlap', 'one chunk per document', 'fixed with no overlap'], a: 1,
  e: 'Right often enough that the argument is not worth having. Move to document-aware the moment your corpus has structure.' },
{ topic: 'rag', q: 'Query and document embeddings must come from...', o: ['different models for diversity', 'the same model', 'any model with the same dimensions', 'a reranker'], a: 1,
  e: 'Embeddings are only comparable within the space that produced them. Mixing models produces valid numbers and meaningless results, with no error.' },
{ topic: 'rag', q: 'Post-filtering a vector search can silently...', o: ['improve recall', 'return fewer than k results, or none', 'change the embedding', 'increase precision to 1.0'], a: 1,
  e: 'Ask for 10, filter to 2, and answer quality collapses with no error. Prefer filtered ANN that pushes the predicate into the traversal.' },
{ topic: 'rag', q: 'Retrieval returned nothing. The WRONG move is to...', o: ['refuse with a specific message', 'pass the empty context to the model anyway', 'relax filters and retry once', 'log it and alarm on the rate'], a: 1,
  e: 'The model then answers from parametric memory, confidently and without citations. It is the single largest source of production hallucination.' },
{ topic: 'rag', q: 'A better confidence signal than absolute cosine similarity is...', o: ['the top-1 score', 'the score GAP between rank 1 and rank 5', 'the number of results', 'the query length'], a: 1,
  e: 'Absolute scores are uncalibrated and drift with the corpus. A flat distribution means the retriever is guessing.' },
{ topic: 'rag', q: 'A 1M-token context window means RAG is...', o: ['obsolete', 'still needed for cost', 'only needed for code', 'only needed above 10M documents'], a: 1,
  e: 'You pay for every token every request, prefill takes seconds, accuracy sags in the middle, and everything in the window is visible regardless of who is asking.' },
{ topic: 'rag', q: 'Agentic RAG earns its extra cost on...', o: ['simple lookups', 'multi-hop and ambiguous questions needing decomposition', 'reducing embedding cost', 'shrinking the index'], a: 1,
  e: 'One embedding of a two-part question sits in the average of two meanings and retrieves neither well. On a simple lookup it just costs more.' },
{ topic: 'rag', q: 'GraphRAG is worth its indexing cost when users ask...', o: ['single-fact lookups that must be exactly right', 'global questions about themes and relationships across a corpus', 'questions arriving in many different languages', 'questions about events more recent than the index'], a: 1,
  e: 'Those answers live in no single chunk. For lookup questions it is expensive overkill.' },
{ topic: 'rag', q: 'CAG (cache-augmented generation) requires that...', o: ['the corpus fits in the context window', 'you use a reranker', 'documents change hourly', 'you have a graph database'], a: 1,
  e: 'Preload the corpus and precompute its KV cache. No retrieval hop, lowest latency, and a hard size ceiling with cache invalidation on every update.' },
{ topic: 'rag', q: 'The first thing to check when Arabic retrieval fails but English works is...', o: ['the reranker', 'whether the embedding model is genuinely multilingual', 'the temperature', 'the context window'], a: 1,
  e: 'Embed one Arabic document and its Arabic question and print the cosine. If a document that answers the question scores near the corpus average, stop there.' },
{ topic: 'rag', q: 'What makes RAG cache invalidation nearly automatic?', o: ['setting a short TTL on every cached answer', 'including a hash of retrieved chunk ids and versions in the cache key', 'allocating a larger cache so fewer entries are evicted early', 'disabling the semantic layer and keeping only exact matches'], a: 1,
  e: 'Change a document, its version changes, the key changes, old answers stop matching. Invalidation becomes a naming problem.' },
{ topic: 'rag', q: 'The most common mistake teams make with RAG is...', o: ['using the wrong vector database', 'shipping with no way to measure retrieval quality', 'chunking too small', 'not fine-tuning'], a: 1,
  e: 'Then every complaint is blamed on "the model hallucinating" while the answering chunk was never in the top 50. Fifty labelled questions fixes this.' },
{ topic: 'rag', q: 'Increasing k from 5 to 20 typically...', o: ['reliably improves answers, since more context is more information', 'raises recall and lowers context precision, often hurting the answer', 'reduces cost, because fewer follow-up questions are needed', 'has no measurable effect once a reranker is in place'], a: 1,
  e: 'More chunks means more noise, more tokens, and the right chunk buried in the middle. Retrieve wide, rerank narrow.' },
{ topic: 'rag', q: 'OKF, as used in interviews, most commonly means...', o: ['a compressed vector index format for billion-scale corpora', 'a governed semantic layer over enterprise knowledge and access policy', 'an open-source RAG library maintained by a foundation', 'a chunking algorithm that cuts on ontology boundaries'], a: 1,
  e: 'It is not a standardised term. It is a data architecture, not a retrieval technique — and asking which definition they mean is a good move.' },

/* ---------------- vectors ---------------- */
{ topic: 'vectors', q: 'On unit-normalised vectors, cosine similarity and dot product...', o: ['differ substantially', 'are identical', 'are inverses', 'cannot be compared'], a: 1,
  e: 'Normalise once at index time and use dot product — same ranking, one fewer division per comparison.' },
{ topic: 'vectors', q: 'HNSW\'s query-time recall dial is...', o: ['M', 'ef_search', 'ef_construction', 'nprobe'], a: 1,
  e: 'M and ef_construction are build-time; nprobe belongs to IVF. ef_search is what you tune in production.' },
{ topic: 'vectors', q: 'IVF misses a true neighbour when...', o: ['the vector is normalised', 'it sits in a cell the query did not probe', 'the index is too small', 'the metric is cosine'], a: 1,
  e: 'Raising nprobe recovers them at a proportional cost in vectors scanned. That is the entire trade.' },
{ topic: 'vectors', q: 'Product quantisation reduces a 768-dim float32 vector from 3,072 bytes to roughly...', o: ['1,536 bytes', '96 bytes', '768 bytes', '8 bytes'], a: 1,
  e: 'With m=96 subvectors each stored as one byte code. Usually paired with a rerank pass over exact vectors to recover recall.' },
{ topic: 'vectors', q: 'At 1.2 billion 768-dim float32 vectors, the binding constraint is...', o: ['query latency', 'memory — about 3.4 TB of raw vectors', 'recall', 'the embedding model'], a: 1,
  e: 'Quote the arithmetic before discussing algorithms. The index choice falls out of the memory number.' },
{ topic: 'vectors', q: 'BM25\'s saturation term exists to stop...', o: ['long documents winning', 'a document that repeats a term ninety times from dominating', 'rare terms scoring highly', 'stop words matching'], a: 1,
  e: 'That saturation is the difference between BM25 and naive TF-IDF, and it is why BM25 won.' },
{ topic: 'vectors', q: 'In Elasticsearch, tenant_id belongs in...', o: ['query context', 'filter context', 'the analyzer', 'the mapping only'], a: 1,
  e: 'Filter context answers yes/no, is cached as a bitset and computes no score. A permission expressed as a ranking signal is not a permission.' },
{ topic: 'vectors', q: 'The most common cause of "nothing matches" in a lexical index is...', o: ['too few shards', 'the analyzer differing between index and query time', 'BM25 parameters', 'a missing reranker'], a: 1,
  e: 'Every query runs successfully and returns zero results. Inspect the analysed terms before debugging anything else.' },
{ topic: 'vectors', q: 'Elasticsearch shard count...', o: ['can be changed live', 'is fixed at index creation and needs a reindex to change', 'is per document', 'only matters for writes'], a: 1,
  e: 'Aim for 10-50 GB per shard and think before you type. Replicas, by contrast, can be changed at any time.' },
{ topic: 'vectors', q: 'A cross-encoder cannot be used for first-stage retrieval because...', o: ['it is measurably less accurate than a bi-encoder', 'it must run per (query, document) pair and cannot be precomputed', 'it requires a GPU, which first-stage retrieval does not have', 'it only works on short passages, not full documents'], a: 1,
  e: 'A bi-encoder precomputes document vectors; a cross-encoder reads the pair together. That is exactly why it is more accurate and why it is a second stage.' },
{ topic: 'vectors', q: 'Matryoshka embeddings let you...', o: ['store multiple models in one index', 'truncate the vector to fewer dimensions with a small accuracy cost', 'skip normalisation', 'search without an index'], a: 1,
  e: 'Information is ordered by importance, so a prefix is a usable embedding. Re-normalise after truncating, and truncate queries and documents identically.' },
{ topic: 'vectors', q: 'Deletes in HNSW are usually...', o: ['immediate and complete', 'soft (tombstones)', 'not supported', 'faster than inserts'], a: 1,
  e: 'Which matters for compliance: "filtered out at query time" is not deletion. Monitor the tombstone ratio and schedule rebuilds.' },
{ topic: 'vectors', q: 'Scatter-gather sharding hurts latency because...', o: ['each shard is slower', 'p95 becomes the p95 of the maximum across all shards', 'network overhead dominates', 'results must be re-embedded'], a: 1,
  e: 'With 20 shards you wait for the slowest of 20. Hedge, or accept partial results after a deadline.' },
{ topic: 'vectors', q: 'Semantic similarity and relevance differ because...', o: ['they are computed with different distance metrics', 'two texts can share a topic and still not answer each other', 'relevance can only be judged by a model, similarity by maths', 'similarity scores are always higher than relevance scores'], a: 1,
  e: '"How do I cancel" and "why did it renew" are very similar and want different answers. That gap is the theoretical justification for reranking.' },
{ topic: 'vectors', q: 'SPLADE produces...', o: ['dense vectors trained with a contrastive objective', 'sparse vectors over the vocabulary with learned term expansion', 'graph embeddings derived from an entity knowledge graph', 'binary hashes compared with Hamming distance'], a: 1,
  e: 'It runs on an inverted index, keeping lexical efficiency and exact-match strength while adding semantic expansion.' },

/* ---------------- agents ---------------- */
{ topic: 'agents', q: 'What defines an agent versus a chain?', o: ['it uses tools', 'the model decides the control flow at run time', 'it has memory', 'it runs asynchronously'], a: 1,
  e: 'A chain\'s steps are fixed by you. In an agent, what happens next depends on what the model just observed.' },
{ topic: 'agents', q: 'Function calling and tool calling are...', o: ['completely different mechanisms', 'the same mechanism under two names', 'only available on open models', 'mutually exclusive'], a: 1,
  e: 'Same JSON-schema-in, structured-call-out mechanism. "Tool" is the newer, more general name because a tool need not be a function you wrote.' },
{ topic: 'agents', q: 'When the model emits a tool call, who executes it?', o: ['the model', 'your code', 'the tokenizer', 'the inference server'], a: 1,
  e: 'The model emits a request; your code decides whether to honour it. That boundary is where every permission check lives.' },
{ topic: 'agents', q: 'A free-text "status" parameter instead of an enum causes...', o: ['a measurably higher cost per tool call', 'silent empty results when the model sends "open" instead of "OPEN"', 'noticeably slower inference on every tool-using request', 'loud schema validation errors the model can recover from'], a: 1,
  e: 'An enum converts a recoverable silent failure into an impossible one. Where you cannot use one, make the error name the legal values.' },
{ topic: 'agents', q: 'The most underrated harness layer is...', o: ['the system prompt', 'observation shaping', 'the model choice', 'the temperature'], a: 1,
  e: 'Six projected fields instead of a 38k-token payload often beats a model upgrade, because the blob buries the answer and evicts the task.' },
{ topic: 'agents', q: 'An agent forgets its instructions at turn 50. Most likely cause?', o: ['the model degrading as the conversation gets longer', 'silent truncation dropping the oldest messages, system prompt included', 'sampling temperature drifting upward across a long session', 'the retrieval index going stale partway through the conversation'], a: 1,
  e: 'No error is raised. Own the trimming: pin the system prompt and the task, drop from the middle, and log token counts.' },
{ topic: 'agents', q: 'Which guard most directly prevents an expensive agent loop?', o: ['a lower temperature, so the agent wanders less', 'a per-request budget in tokens and money, checked before each call', 'a larger context window so it does not lose the task', 'more tools, so it finds the answer in fewer steps'], a: 1,
  e: 'Plus a repeat-call detector: the same tool with identical arguments twice in a row is almost always a bug.' },
{ topic: 'agents', q: 'The stop sequence in a ReAct loop prevents...', o: ['long answers', 'the model hallucinating its own tool results', 'high cost', 'tool errors'], a: 1,
  e: 'If you see plausible tool results that never happened, check the stop sequence first. It is the classic hand-rolled-loop bug.' },
{ topic: 'agents', q: 'Plan-and-execute beats ReAct mainly when...', o: ['the task is exploratory and the shape is unknown', 'the task has side effects and a human should approve the plan', 'latency does not matter and you can afford many calls', 'there is only one tool, so ordering is trivial'], a: 1,
  e: 'Fewer expensive calls and a natural approval point. It is less adaptive, so it needs an explicit replan trigger.' },
{ topic: 'agents', q: 'The hardest part of a multi-agent system is usually...', o: ['choosing models', 'the handoff message between agents', 'the number of tools', 'streaming'], a: 1,
  e: 'What one agent tells the next is a lossy summary. Make the handoff a typed schema rather than free prose.' },
{ topic: 'agents', q: 'Human-in-the-loop approval requires which engineering capability?', o: ['token streaming, so the reviewer sees progress', 'durable checkpointing, so a run can pause for hours and resume', 'a larger model that makes fewer decisions needing approval', 'a fine-tune that teaches the model when to ask permission'], a: 1,
  e: 'It is a durability feature before it is a safety feature. That is why LangGraph makes checkpointing first class.' },
{ topic: 'agents', q: 'An agent times out and retries a refund. What prevents a double refund?', o: ['a lower temperature', 'an idempotency key derived from the action', 'a step cap', 'a smaller prompt'], a: 1,
  e: 'The key must come from the ACTION, not from the attempt. A random uuid per retry makes every retry a new action.' },
{ topic: 'agents', q: 'Agent evaluation differs from model evaluation because you must verify...', o: ['the exact wording', 'the END STATE, not the agent\'s own report', 'the token count', 'the temperature'], a: 1,
  e: 'An agent can produce a beautifully written summary of a task it never completed, and a judge reading the transcript will confirm it.' },
{ topic: 'agents', q: 'The most useful agent cost metric is...', o: ['cost per call', 'cost per SUCCESSFUL task', 'total monthly spend', 'tokens per second'], a: 1,
  e: '60% success at $0.10 is worse than 85% at $0.25, and only the per-success figure shows it.' },
{ topic: 'agents', q: 'MCP standardises...', o: ['the format model weights are distributed in', 'how applications expose tools, resources and prompts to LLMs', 'the tokenizer vocabulary shared between providers', 'the metrics used to evaluate agent trajectories'], a: 1,
  e: 'It turns N clients x M servers into N + M integrations. Treat third-party servers as dependencies with permissions.' },
{ topic: 'agents', q: 'If 20% of your agent runs terminate at the step cap, you should...', o: ['raise the cap so more runs get the chance to finish', 'investigate, because the cap is a symptom detector not a control', 'lower the temperature so the agent commits earlier', 'add more tools so it has more ways to make progress'], a: 1,
  e: 'Raising it usually just costs more before failing. Something upstream — a broken tool, a task the tools cannot do, a loop — is the real issue.' },

/* ---------------- eval ---------------- */
{ topic: 'eval', q: 'The base of a healthy eval pyramid is...', o: ['LLM judges', 'deterministic assertions', 'human review', 'A/B tests'], a: 1,
  e: 'Roughly 60% assertions, 20% retrieval metrics, 15% judge, 5% human. The judge is near the top, never the base.' },
{ topic: 'eval', q: 'An LLM judge is defensible mainly because...', o: ['a model grading output does not hallucinate the way a generator does', 'discrimination is easier than generation, and agreement is measurable', 'the judge is always a larger model than the one being graded', 'running the judge at temperature 0 makes its verdicts reliable'], a: 1,
  e: 'Label 100 cases by hand and report kappa. Below about 0.6 the judge is noise wearing a lab coat.' },
{ topic: 'eval', q: 'The judge mitigation with the largest single gain is usually...', o: ['a longer prompt', 'position swap', 'higher temperature', 'a bigger judge model'], a: 1,
  e: 'Position bias is the largest documented judge bias, and the swap costs exactly 2x to remove it.' },
{ topic: 'eval', q: 'Semantic similarity is a bad correctness metric because it cannot distinguish...', o: ['synonyms', '"refunds take 5 days" from "refunds take 50 days"', 'languages', 'long from short answers'], a: 1,
  e: 'Those embed almost identically. Never use it alone for factual correctness.' },
{ topic: 'eval', q: 'Pairwise comparison beats absolute scoring because it...', o: ['is cheaper', 'avoids scale calibration entirely', 'needs no judge', 'is faster'], a: 1,
  e: 'Models rank far more reliably than they score. The cost is that you get a ranking, not a level.' },
{ topic: 'eval', q: 'Which RAGAS metric needs ground-truth relevant documents?', o: ['faithfulness', 'context recall', 'answer relevance', 'context precision'], a: 1,
  e: 'Which is why it is the metric nobody builds. Faithfulness needs no ground truth, so it can run on production traffic.' },
{ topic: 'eval', q: 'Faithfulness measures...', o: ['whether the answer is true', 'whether every claim is supported by the retrieved context', 'answer length', 'retrieval speed'], a: 1,
  e: 'An answer can be true and unfaithful — the model knew it already — which is a failure for a grounded product.' },
{ topic: 'eval', q: 'An eval set should include out-of-scope questions because...', o: ['it pads the numbers', 'otherwise you never notice the system fails to refuse', 'they are cheap to write', 'judges prefer them'], a: 1,
  e: 'Without them your system scores well by answering everything, and you discover the problem when a customer acts on a fabricated answer.' },
{ topic: 'eval', q: 'Offline evals improved and production got worse. The most likely cause is...', o: ['the provider silently changed the model behind an alias', 'the eval set does not represent real traffic, or latency regressed', 'the judge model is broken and its scores are meaningless', 'random noise; production metrics are inherently unstable'], a: 1,
  e: 'Sample fifty real failures and check how many resemble anything in the eval set. Usually very few, and that is the finding.' },
{ topic: 'eval', q: 'Cohen\'s kappa corrects agreement for...', o: ['sample size', 'agreement expected by chance', 'annotator experience', 'class imbalance only'], a: 1,
  e: 'Two annotators who both say "good" 90% of the time agree 81% by luck alone. Measure it between humans before trusting any labels.' },
{ topic: 'eval', q: 'A frozen judge means...', o: ['temperature 0', 'the judge model version AND prompt are pinned', 'a local model', 'no self-consistency'], a: 1,
  e: 'If both the system and the ruler move between releases, you have measured nothing.' },
{ topic: 'eval', q: 'For a code-generating feature, the gold-standard metric is...', o: ['BLEU against a reference', 'execution — does it compile and pass the tests', 'embedding similarity', 'human preference'], a: 1,
  e: 'Everything else is a proxy. Report pass@1 at temperature 0 for a product; pass@10 is a research metric.' },
{ topic: 'eval', q: 'Which product signal indicates a bad answer without any labelling?', o: ['session length', 'the user immediately rephrasing the same question', 'time of day', 'response length'], a: 1,
  e: 'Follow-up rephrase rate is a strong implicit signal and it is free to measure.' },
{ topic: 'eval', q: 'A canary rollout that looks slower and more expensive than expected may simply have...', o: ['a bug', 'a cold prompt cache', 'the wrong model', 'too little traffic'], a: 1,
  e: 'Give it time to warm before judging. Teams roll back good changes for this reason.' },
{ topic: 'eval', q: 'The minimum viable eval for a team shipping next week is...', o: ['a full LLM-as-judge harness with rubrics', '20-50 real cases, five deterministic assertions and a script', 'an A/B test running against a slice of real traffic', 'a RAGAS integration reporting all four of its metrics'], a: 1,
  e: 'A spreadsheet in week one beats perfect infrastructure in month three. Every production bug then becomes case 51.' },

/* ---------------- safety ---------------- */
{ topic: 'safety', q: 'Which guardrail layer actually cannot be argued past?', o: ['the system prompt', 'code-level action guards', 'an input classifier', 'an output classifier'], a: 1,
  e: 'A prompt reduces the frequency of bad behaviour; code prevents it. Anything that must never happen belongs in code.' },
{ topic: 'safety', q: 'Indirect prompt injection is more dangerous than a jailbreak because...', o: ['it is harder to detect', 'the user is a victim', 'it only affects open models', 'it bypasses rate limits'], a: 1,
  e: 'A third party controls content the agent reads, and the agent can call tools, spend money and send messages.' },
{ topic: 'safety', q: 'The strongest defence against indirect injection is...', o: ['a better system prompt', 'least-privilege tools and egress allowlisting', 'higher temperature', 'a longer delimiter'], a: 1,
  e: 'Assume some injections will succeed and make sure the blast radius is small. Prompt-based defences reduce the rate, not the risk.' },
{ topic: 'safety', q: 'Rendering a model-produced markdown image URL can...', o: ['do nothing at all, since it is only rendered text', 'exfiltrate the conversation to an attacker with no tool involved', 'crash the renderer if the image cannot be fetched', 'leak only harmless metadata such as the user agent'], a: 1,
  e: 'The user\'s browser fetches the URL. Allowlist image hosts and sanitise output even in a read-only assistant.' },
{ topic: 'safety', q: 'Memory poisoning is worse than a one-off hallucination because...', o: ['it is much harder to detect in a single response', 'the false fact persists and is later retrieved as trusted context', 'it consumes far more tokens than an ordinary mistake', 'it adds latency to every subsequent memory lookup'], a: 1,
  e: 'Never extract memories from untrusted content, store provenance, and treat the memory write path like a tool permission.' },
{ topic: 'safety', q: 'Over-refusal matters because...', o: ['it looks bad on published safety benchmarks', 'refusing legitimate requests frustrates users and shows up as escalations', 'every refusal still costs a full inference call', 'refusals cannot be streamed to the client'], a: 1,
  e: 'Safety is two-sided. A team reporting 0% harmful output that never measured over-refusal has optimised one side of a trade-off.' },
{ topic: 'safety', q: 'The most common cause of cross-tenant data leakage is...', o: ['the model memorising data', 'a cache key without a tenant component', 'a weak system prompt', 'streaming'], a: 1,
  e: 'Everything else can be correct and a shared answer cache leaks on the first hit. Write the CI test.' },
{ topic: 'safety', q: 'Fine-tuning on entirely benign data...', o: ['always improves safety', 'can measurably weaken safety alignment', 'has no effect on safety', 'only affects formatting'], a: 1,
  e: 'Which is why you re-run the safety suite after every tune, not just the task metric.' },
{ topic: 'safety', q: 'Model output should be treated as...', o: ['trusted', 'untrusted input to whatever consumes it next', 'validated by the provider', 'safe if the temperature is 0'], a: 1,
  e: 'Never eval it, never interpolate it into SQL, never render it as raw HTML. It may have been dictated by a document the model read.' },
{ topic: 'safety', q: 'Loading a PyTorch .bin checkpoint can...', o: ['never be unsafe', 'execute arbitrary code', 'only fail to load', 'corrupt the GPU'], a: 1,
  e: 'Safetensors exists specifically to prevent this. "We only load safetensors" is a good policy to be able to state.' },
{ topic: 'safety', q: 'The dual-LLM pattern separates...', o: ['the training environment from the inference environment', 'the model that reads untrusted content from the one holding permissions', 'the model being judged from the model doing the judging', 'input-side guardrails from output-side guardrails'], a: 1,
  e: 'The quarantined model returns structured data only, validated against a schema before crossing the boundary.' },
{ topic: 'safety', q: 'A sandbox for generated code must, above all, restrict...', o: ['CPU', 'network access', 'disk size', 'the language'], a: 1,
  e: 'With network access, generated code can exfiltrate anything it can read. Pre-install dependencies rather than allowing installs.' },
{ topic: 'safety', q: 'Rate limiting by request count alone misses...', o: ['slow clients', 'the expensive-request attack', 'authenticated users', 'batch traffic'], a: 1,
  e: 'The asymmetry is the point: an attacker spends one HTTP request and you spend dollars of GPU time. Limit by cost.' },
{ topic: 'safety', q: 'PII most commonly leaks out of an LLM system through...', o: ['the model\'s weights', 'observability', 'the tokenizer', 'the vector index'], a: 1,
  e: 'Tracing captures prompts by default, which puts personal data in your tracing vendor. Redact before logging, not after.' },
{ topic: 'safety', q: 'In a regulated setting, using a floating model alias like "latest" is...', o: ['best practice', 'a compliance problem', 'required for security', 'irrelevant'], a: 1,
  e: 'The provider updating a model behind an alias means the decision cannot be reproduced or explained. Pin explicit versions.' },

/* ---------------- production ---------------- */
{ topic: 'production', q: 'The single largest cost lever in most LLM applications is...', o: ['a smaller model', 'prompt caching', 'shorter outputs', 'batch APIs'], a: 1,
  e: 'Up to about 90% off input tokens for a stable prefix, and it is nearly free to adopt. Routing is usually the second-largest.' },
{ topic: 'production', q: 'You should alarm on...', o: ['total monthly spend only', 'cost per request p99', 'the number of API calls', 'GPU temperature'], a: 1,
  e: 'Total spend hides the handful of catastrophic requests — the agent that looped forty times — which are your biggest risk and easiest fix.' },
{ topic: 'production', q: 'Which is NOT a way to reduce time to first token?', o: ['prompt caching', 'streaming', 'a shorter prompt', 'a smaller model'], a: 1,
  e: 'Streaming changes what happens after the first token. TTFT is unaffected, and it is the number users feel as "is it broken?".' },
{ topic: 'production', q: 'When a latency budget is broken down, the largest term is often...', o: ['network', 'decode — the length of the answer', 'the tokenizer', 'authentication'], a: 1,
  e: 'And it is the easiest to reduce: ask for a shorter answer. Teams optimise retrieval for weeks and never cap max_tokens.' },
{ topic: 'production', q: 'A degraded answer (fallback model, trimmed prompt) must never be...', o: ['returned to the user', 'written to the cache', 'logged', 'streamed'], a: 1,
  e: 'Caching it turns a thirty-second incident into a permanent quality regression nobody can find.' },
{ topic: 'production', q: 'The prompt cache hit rate suddenly dropped to zero. Most likely cause?', o: ['an outage or configuration change at the provider', 'something volatile was added near the TOP of the prompt', 'the sampling temperature was changed by another team', 'a traffic increase pushing entries out of the cache'], a: 1,
  e: 'A timestamp, request id or shuffled tool list. Move it to the bottom, and alarm on hit rate so you find it in hours rather than at month end.' },
{ topic: 'production', q: 'A circuit breaker should be paired with...', o: ['a longer timeout', 'a defined fallback path', 'more retries', 'a bigger queue'], a: 1,
  e: 'An open circuit that returns errors is only marginally better than timeouts. One that routes to a smaller model keeps the product working.' },
{ topic: 'production', q: 'Which should be versioned together as one release artifact?', o: ['code only', 'prompt version', 'prompts only', 'the eval set only'], a: 1,
  e: 'A rollback that reverts the prompt but not the index gives you a combination that was never tested.' },
{ topic: 'production', q: 'Your kill switch requires a deploy. What is the consequence?', o: ['none, as long as deploys are reasonably fast', 'your mean time to containment is your deploy time', 'a higher cost per incident because of wasted calls', 'worse latency while the deploy is rolling out'], a: 1,
  e: 'And that number ends up in the incident report. Prompt version, model choice and feature flags must be runtime config.' },
{ topic: 'production', q: 'A framework like LangChain primarily gives you...', o: ['a better model', 'integrations, plumbing and provider abstraction', 'lower cost', 'higher accuracy'], a: 1,
  e: 'At the cost of visibility into the exact prompt. Use the pieces; always be able to print what was actually sent.' },
{ topic: 'production', q: 'Autoscaling GPU inference should trigger on...', o: ['CPU utilisation', 'queue depth or KV cache occupancy', 'memory usage', 'request count only'], a: 1,
  e: 'And it must account for cold-start time, which is minutes for a large model — so scale-to-zero is usually unacceptable for interactive traffic.' },
{ topic: 'production', q: 'Model routing typically saves...', o: ['5-10%', 'a majority of spend', 'nothing without fine-tuning', 'only latency'], a: 1,
  e: 'If 70% goes to a model costing a twentieth as much, total spend falls by roughly 65%. Measure quality per route separately.' },
{ topic: 'production', q: 'The most reliable escalation signal for a cascade is...', o: ['the model saying it is unsure', 'a verifiable check', 'response length', 'latency'], a: 1,
  e: 'Self-reported confidence is weak and uncalibrated. Mechanical checks are free and never hallucinate.' },
{ topic: 'production', q: 'A batch API is typically...', o: ['faster', 'about 50% cheaper with a longer completion window', 'more accurate', 'only for embeddings'], a: 1,
  e: 'Right for backfills, offline classification, evaluation runs and nightly summarisation. Separate interactive and batch paths from day one.' },
{ topic: 'production', q: 'What breaks first when traffic grows 10x?', o: ['the model', 'provider rate limits', 'the tokenizer', 'the CSS'], a: 1,
  e: 'Then cost, then queueing latency, then the index, then the human processes — the escalation queue and the on-call rota.' },

/* ---------------- data ---------------- */
{ topic: 'data', q: 'A 5 GB CSV on a 2 GB machine. The first thing you say is...', o: ['provision a machine with enough RAM to hold the file', 'stream it, so memory is bounded by the row plus the running state', 'split it into 100 smaller files and process them in sequence', 'move the job to a Spark cluster that can hold it in memory'], a: 1,
  e: 'The file size is never the constraint; the largest live object is. Then name the state as the thing that can still blow up.' },
{ topic: 'data', q: 'You streamed the file and it still died on a group-by with 50 million keys. Now what?', o: ['stream in smaller pieces so less is held at any moment', 'partition by hash of the key into N spill files, then aggregate each', 'increase the chunk size so there are fewer aggregation steps', 'sort the whole file by key first, then aggregate in one pass'], a: 1,
  e: 'External group-by. Equal keys hash to the same partition, so each partition fits in memory. Fifteen lines, and it always works.' },
{ topic: 'data', q: 'The most common way engineers accidentally undo chunked reading is...', o: ['too small a chunk size', 'appending chunks to a list and concatenating at the end', 'using usecols', 'category dtypes'], a: 1,
  e: 'That loads the whole file with extra steps. Reduce inside the loop or you have not streamed anything.' },
{ topic: 'data', q: 'A Python generator is single-use. Iterating it twice gives...', o: ['an error', 'nothing on the second pass, silently', 'the same items again', 'a copy'], a: 1,
  e: 'If you need two passes, re-create it. If you materialise it, you are back to holding everything.' },
{ topic: 'data', q: 'Converting CSV to Parquet is worth it when...', o: ['never', 'you will query the data more than about twice', 'the file is under 1 GB', 'you need row-level updates'], a: 1,
  e: 'Columnar, typed, compressed, with projection and predicate pushdown. CSV parsing was usually most of the cost.' },
{ topic: 'data', q: 'For a single 5 GB file on one machine, Spark is usually...', o: ['the fastest option', 'slower than DuckDB or Polars', 'required', 'the cheapest option'], a: 1,
  e: 'Reach for a cluster when the data genuinely exceeds one machine, not to look sophisticated.' },
{ topic: 'data', q: 'Idempotent ingestion requires...', o: ['a freshly generated uuid for every chunk written', 'a deterministic id derived from document, section and content hash', 'a write timestamp so later versions overwrite earlier ones', 'a pipeline that never retries, so nothing is ever written twice'], a: 1,
  e: 'Then a replay overwrites rather than duplicating, and a partial failure can simply be re-run.' },
{ topic: 'data', q: 'The most commonly missing path in a RAG ingestion pipeline is...', o: ['chunking', 'delete propagation', 'embedding', 'metadata'], a: 1,
  e: 'Ask anyone whose RAG has been live a year whether a deleted document is still retrievable. Often it is.' },
{ topic: 'data', q: 'Near-duplicate detection at scale usually uses...', o: ['exact hashing', 'MinHash with locality-sensitive hashing', 'sorting', 'BM25'], a: 1,
  e: 'Similar documents get similar signatures and collide into the same bucket, making the comparison sub-quadratic.' },
{ topic: 'data', q: 'Backpressure in an embedding pipeline prevents...', o: ['the embedding provider rate limiting your requests', 'an unbounded in-memory queue when the reader outpaces the API', 'duplicate chunks being written when a batch is retried', 'schema drift between the reader and the index'], a: 1,
  e: 'Bounded queues, a semaphore on in-flight requests, and retry with a dead-letter queue.' },
{ topic: 'data', q: 'When splitting production logs into train and test, split by...', o: ['random sampling', 'time, holding out the most recent slice', 'user id', 'document length'], a: 1,
  e: 'A random split leaks future distribution into training and inflates your eval.' },
{ topic: 'data', q: 'A dead-letter queue nobody monitors is equivalent to...', o: ['a retry', 'silently dropping the data', 'a backup', 'a cache'], a: 1,
  e: 'And it fails in the way that produces "why can I not find this document" tickets months later. Alarm on depth.' },
{ topic: 'data', q: 'PDF text extraction most often fails on...', o: ['file size', 'multi-column layouts and tables', 'encryption', 'colour'], a: 1,
  e: 'Sample the extracted text and read it. Teams debug retrieval for weeks when every table became a row of unrelated numbers.' },
{ topic: 'data', q: 'Chunk size should be chosen by...', o: ['convention', 'sweeping sizes and overlaps against a labelled eval set', 'the model\'s context window', 'the document length'], a: 1,
  e: 'An afternoon of compute settles the argument permanently, and the optimum changes when the corpus or the embedder changes.' },
{ topic: 'data', q: 'For non-Latin scripts, chunk size should be measured in...', o: ['tokens', 'characters or words', 'sentences only', 'bytes'], a: 1,
  e: 'Tokenisers inflate non-Latin text, so a 500-token chunk holds a fraction of the content an English chunk holds.' },

/* ---------------- system design ---------------- */
{ topic: 'sysdesign', q: 'What is the strongest signal a candidate can give in an AI system design round?', o: ['naming as many techniques as possible', 'doing the traffic and cost arithmetic out loud', 'drawing the most detailed diagram', 'choosing the newest model available'], a: 1,
  e: '"20 requests a second times 4,000 input tokens at $3 per million is about $95,000 a month" reframes the whole design, and almost nobody does it.' },
{ topic: 'sysdesign', q: 'In a support assistant, live account state should come from...', o: ['the vector index, refreshed nightly', 'a tool call at question time', 'the system prompt', 'a fine-tuned model'], a: 1,
  e: 'Documents belong in the index; live state belongs behind an API. Trying to keep an index fresh for data that changes by the second is a race you do not need to run.' },
{ topic: 'sysdesign', q: 'At 50 million documents, which does most for both latency and quality?', o: ['a better reranker on the top 100', 'metadata and permission filtering before the vector search', 'a larger embedding dimension', 'more replicas of the index'], a: 1,
  e: 'Filtering cuts the candidate space by orders of magnitude before similarity is ever computed. Ranking improvements operate on what is left.' },
{ topic: 'sysdesign', q: 'For a hard 500 ms end-to-end budget, which is the first thing to drop?', o: ['prompt caching', 'the cross-encoder reranker on the critical path', 'structured output', 'the retrieval step entirely'], a: 1,
  e: 'A reranker is commonly 80-400 ms. Caching and structured output are cheap or free; dropping retrieval changes what the product is.' },
{ topic: 'sysdesign', q: 'Which is the most valuable corpus for a SaaS support assistant, and the hardest to use?', o: ['the marketing site', 'past resolved tickets', 'the API reference', 'release notes'], a: 1,
  e: 'They contain the real questions and the real answers - and PII, shorthand, and answers that were correct before a fix shipped. Curate, do not dump.' },
{ topic: 'sysdesign', q: 'In a multi-tenant AI platform, per-tenant dashboards matter because...', o: ['tenants ask for them', 'aggregate metrics hide the one customer having a terrible week', 'they are cheaper to compute', 'they replace the need for tracing'], a: 1,
  e: 'And that customer is the one who will tell you first, usually by leaving.' },
{ topic: 'sysdesign', q: 'A question involving counting or filtering over records should be routed to...', o: ['a larger context window', 'text-to-SQL against a read-only connection', 'more retrieved chunks', 'a reranker tuned for numbers'], a: 1,
  e: 'A model cannot reliably sum a column in a prompt. Recognising that a question is an aggregation is the whole job of the router.' },
{ topic: 'sysdesign', q: 'For an extraction pipeline, the metric the business cares about is...', o: ['field-level accuracy', 'straight-through-processing rate', 'tokens per document', 'model latency'], a: 1,
  e: '95% field accuracy across twenty fields still means most documents need a human touch. Only the document-level number tells you the saving.' },

/* ---------------- tooling & ecosystem ---------------- */
{ topic: 'tooling', q: 'Which is NOT a vector database?', o: ['Qdrant', 'Weaviate', 'Unstructured', 'Milvus'], a: 2,
  e: 'Unstructured is document ingestion — it turns PDFs and Word files into typed elements. It sits several stages before storage in the pipeline.' },
{ topic: 'tooling', q: 'MCP primarily solves which problem?', o: ['Making inference cheaper', 'The N-clients-by-M-tools integration explosion', 'Vector search recall', 'Prompt optimisation'], a: 1,
  e: 'Without a protocol, every client writes its own wrapper for every tool. MCP makes it write-once, use-anywhere — the same argument as LSP for editors.' },
{ topic: 'tooling', q: 'Retrieval returns the right chunk at rank 14 of 20 and the answer is still wrong. Best next move?', o: ['Switch to a bigger generation model', 'Add a cross-encoder reranker', 'Increase chunk size', 'Fine-tune the embedding model'], a: 1,
  e: 'The information is retrieved and then buried, so this is an ordering problem. Reranking fixes exactly that stage and is far cheaper than fine-tuning or a bigger model.' },
{ topic: 'tooling', q: 'Which pair does essentially the same job?', o: ['Airflow and Presidio', 'LangSmith and Langfuse', 'vLLM and Pinecone', 'DSPy and Qdrant'], a: 1,
  e: 'Both are LLM observability and evaluation platforms. The real difference is hosting model and framework neutrality, not capability.' },
{ topic: 'tooling', q: 'You must guarantee an agent never sends an email without approval. Which layer?', o: ['A stricter system prompt', 'A tighter output guardrail', 'A human-in-the-loop interrupt before the tool executes', 'A lower temperature'], a: 2,
  e: 'Prompts and classifiers are probabilistic. A gate in your own code before the side effect fires is deterministic. Never defend an irreversible action with a prompt.' },
{ topic: 'tooling', q: 'Your embedding model changes from 1536 to 3072 dimensions. What must happen?', o: ['Nothing, the index adapts', 'Reindex everything — vectors from different models are not comparable', 'Only new documents need embedding', 'Swap the reranker'], a: 1,
  e: 'Different models produce different spaces. Mixing them silently destroys retrieval quality, which is the worst kind of bug because nothing errors.' },
{ topic: 'tooling', q: 'Ollama is the wrong choice for production because it lacks...', o: ['quantisation support', 'continuous batching and a concurrency scheduler', 'an OpenAI-compatible API', 'GPU support'], a: 1,
  e: 'It is a single-user local server. Throughput collapses under concurrency because nothing is batching. vLLM is the production counterpart.' },
{ topic: 'tooling', q: 'A Streamlit chat app reloads the embedding model on every message. The fix is...', o: ['a faster model', 'st.cache_resource around the loader', 'moving the code higher in the file', 'more workers'], a: 1,
  e: 'Streamlit reruns the whole script on every interaction. cache_resource keeps expensive objects alive across reruns; session_state is the only other thing that survives.' },
{ topic: 'tooling', q: 'Why is async the right default for a FastAPI endpoint that calls an LLM?', o: ['It speeds up generation', 'The work is I/O-bound, so one worker holds many in-flight requests', 'It reduces token cost', 'Pydantic requires it'], a: 1,
  e: 'You are waiting on an external network call. Async trades blocked threads for concurrency — but a blocking call inside an async handler stalls the whole event loop and undoes it.' },
{ topic: 'tooling', q: 'Which is a durable-execution engine, not an agent framework?', o: ['Temporal', 'Agno', 'CAMEL', 'PydanticAI'], a: 0,
  e: 'Temporal persists workflow state as an event history, so a workflow survives process death and resumes exactly where it stopped. Agents can sit on top of it.' },
{ topic: 'tooling', q: 'A prototype does 40 requests a day. The team wants to self-host Llama to save money. Best response?', o: ['Agree — self-hosting is always cheaper', 'Do the crossover arithmetic; at that volume a GPU idles and costs more', 'Self-host on CPU instead', 'Use a smaller hosted model without doing the maths'], a: 1,
  e: 'Self-hosting wins on steady high volume, not bursty developer traffic. An idle GPU bills all day for forty calls. The right answer is a number, not a preference.' },
{ topic: 'tooling', q: 'Which tool redacts PII before a hosted model call, with reversible restoration?', o: ['Microsoft Presidio', 'Ragas', 'Prefect', 'BGE'], a: 0,
  e: 'Presidio detects entities with NER, regexes and checksum validators, then anonymises with operators — and its encryption operator is reversible so the response can be rehydrated.' },
{ topic: 'tooling', q: 'The strongest argument against a multi-agent design is...', o: ['agents cannot share tools', 'every extra agent adds a context window, a handoff and a failure mode', 'no framework supports it', 'it is always slower than one call'], a: 1,
  e: 'Multi-agent multiplies cost and loses information at handoffs. Justify it with different tools or different permissions per agent, not with an org chart.' },
{ topic: 'tooling', q: 'What is the RAG Triad?', o: ['Retrieve, augment, generate', 'Context relevance, groundedness, answer relevance', 'Precision, recall, F1', 'Chunk, embed, index'], a: 1,
  e: 'From TruLens. The value is that the three localise the failure: bad context relevance is retrieval, bad groundedness is generation, bad answer relevance is prompting.' },
{ topic: 'tooling', q: 'Which vector store is usually the correct default for a new system?', o: ['Milvus', 'pgvector', 'Pinecone', 'Elasticsearch'], a: 1,
  e: 'One database, transactional consistency with your business data, existing backups, hybrid search in one query. Its ceiling is the low millions of vectors — move only when you measure a reason.' },
{ topic: 'tooling', q: 'Indirect prompt injection arrives via...', o: ['the user typing an attack', 'a retrieved document, web page, email or ticket the agent reads', 'a malformed API request', 'a temperature that is set too high'], a: 1,
  e: 'It is the dangerous kind precisely because nobody is watching that input. A malicious GitHub issue body is a delivery mechanism straight into an agent with commit rights.' },
{ topic: 'tooling', q: 'What does LangGraph give you that a plain agent loop does not?', o: ['cheaper tokens', 'checkpointed state, so a crashed run resumes and a human can approve mid-run', 'better prompts', 'a bigger context window'], a: 1,
  e: 'Checkpointers persist state after every node. That is what makes crash recovery, time travel and interrupt-based human approval possible at all.' },
{ topic: 'tooling', q: 'BGE embedding models underperform their benchmarks most often because teams forget...', o: ['to normalise vectors', 'the instruction prefix on queries', 'to set temperature', 'to use HNSW'], a: 1,
  e: 'BGE expects a query prefix such as "Represent this sentence for searching relevant passages:". Omit it and nothing errors — retrieval just quietly gets worse.' },

/* ---------------- behavioural ---------------- */
{ topic: 'behavioural', q: 'Asked about a project you shipped, which detail signals real operating experience?', o: ['the model you chose', 'the cost per request and the measured outcome', 'the framework you used', 'the size of the team'], a: 1,
  e: '"About $0.04 a request, and it deflected 38% of tickets" is a different answer from "we built a RAG chatbot".' },
{ topic: 'behavioural', q: 'The weakest root cause you can give for a production failure is...', o: ['a missing alarm', '"the model hallucinated"', 'an untested fallback path', 'a cache key without a version'], a: 1,
  e: 'That is the symptom. The cause is almost always upstream: empty retrieval passed through, a missing verification step, a context that silently truncated.' },
{ topic: 'behavioural', q: 'In your first 30 days on an AI team, the highest-value thing you can do is often...', o: ['propose an architecture rewrite', 'read fifty real production transcripts', 'benchmark three new models', 'refactor the prompt library'], a: 1,
  e: 'Most engineers look at dashboards. The ones who read the conversations find the problem nobody had noticed.' },
{ topic: 'behavioural', q: 'The most informative question to ask an interviewer about an AI role is...', o: ['which model do you use', 'how do you evaluate quality, and who owns it', 'what is the team size', 'do you self-host'], a: 1,
  e: 'A team that cannot describe how they measure quality is a team where you will spend your first quarter building that. Better to know first.' },
{ topic: 'behavioural', q: '"Ship it faster" is best negotiated by reducing...', o: ['the controls', 'the scope', 'the eval set', 'the observability'], a: 1,
  e: 'Speed and safety trade in scope, not in controls. A narrow feature with a kill switch can ship this week; a broad one without one cannot ship safely at any speed.' },
{ topic: 'behavioural', q: 'When is "not AI" the right recommendation?', o: ['never, in an AI role', 'when the task is deterministic, specifiable, or already a database query', 'only when the budget is small', 'only for regulated industries'], a: 1,
  e: 'A candidate who has recommended a rules engine or a better search box over an LLM has judgement. One who has never said no has not been in the room long enough.' },
{ topic: 'behavioural', q: '"Good enough to ship" should be measured against...', o: ['perfect accuracy', 'the status quo, plus the safety net you are adding', 'a published benchmark', 'the strongest available model'], a: 1,
  e: '85% accurate with a one-click escalation can be a large improvement on a queue with a two-day response time.' }

/* ---------------- production drills ---------------- */
,{ topic: 'prodops', q: 'You scale from 3 application servers to 30. Your tokens-per-minute quota...', o: ['scales with the fleet automatically', 'is unchanged', 'is divided evenly across the new instances by the provider', 'increases once sustained usage proves you need the extra headroom'], a: 1,
  e: 'Provider quota is an account-level allowance and has nothing to do with your instance count. Ten times the servers hitting one unchanged quota is ten times the 429s.' },
{ topic: 'prodops', q: 'Why add jitter to exponential backoff?', o: ['To spread synchronised retries so recovery is not immediately re-broken', 'To make the average delay shorter than plain exponential growth would give you', 'Because providers reject retries that arrive on exact second boundaries', 'To keep the retry count below the provider rate limit for the window'], a: 0,
  e: 'Without jitter every client that failed at the same instant retries at the same instant. The service comes back, gets a synchronised wave, and falls over again.' },
{ topic: 'prodops', q: 'A circuit breaker in HALF-OPEN state does what?', o: ['Blocks every call until an operator manually resets the dependency', 'Lets one probe call through', 'Sends half the traffic to the failing dependency and half to a fallback path', 'Retries the last failed call with double the previous timeout applied'], a: 1,
  e: 'One probe decides it: success closes the breaker, failure re-opens it and restarts the cool-down. Without the probe state a breaker either never reopens or reopens into the same overload.' },
{ topic: 'prodops', q: 'Which failure should NOT be retried?', o: ['A gateway timeout on a stateless read request', 'A 429 with a Retry-After header attached', 'A schema validation failure on the request you sent', 'A 503 from the provider during a known incident window'], a: 2,
  e: 'A malformed request is malformed on every attempt. Retrying it multiplies cost and latency and changes nothing — classify the error before deciding.' },
{ topic: 'prodops', q: 'What is the main risk of a semantic cache threshold set too low?', o: ['The cache fills up faster than the eviction policy can reclaim space', 'Answers get served for questions with a different meaning', 'Embedding the query becomes the dominant cost of the request', 'Hit rate drops because near-duplicate questions stop matching each other'], a: 1,
  e: 'Similarity measures wording, not intent. "Refunds over 30 days" and "under 30 days" sit very close together and have opposite answers, which is why thresholds run at 0.95 and above.' },
{ topic: 'prodops', q: 'Which single change most often breaks a provider prompt cache?', o: ['Raising max_tokens on the completion request', 'Putting a timestamp near the top of the prompt', 'Switching the sampling temperature between requests', 'Adding retrieved context at the end of the user message'], a: 1,
  e: 'The discount applies to a stable prefix. Anything varying near the top invalidates it for every request, and the bill roughly doubles with no other visible change.' },
{ topic: 'prodops', q: 'The right saturation signal for a queue-backed LLM worker pool is...', o: ['CPU utilisation across the worker instances', 'queue depth and oldest-message age', 'memory pressure reported by the container runtime', 'the ratio of successful to failed provider calls per minute'], a: 1,
  e: 'These workers are blocked on network waits, so CPU stays low through a total backlog. Depth and age are the only honest measure of whether you are keeping up.' },
{ topic: 'prodops', q: 'Load shedding differs from rate limiting because...', o: ['it is applied per tenant rather than across all incoming traffic', 'it is a global response to overload based on request priority', 'it returns 503 rather than 429 so clients know to stop retrying entirely', 'it queues low-priority work instead of rejecting any of it outright'], a: 1,
  e: 'A rate limit is a standing per-tenant policy. Shedding kicks in only under overload and asks what a request is worth, not who sent it.' },
{ topic: 'prodops', q: 'Retrieval returns nothing because the vector database is down. The system should...', o: ['answer from the model’s own knowledge and add a disclaimer to the response', 'abstain or serve a cached answer', 'retry the retrieval call until the database recovers or the deadline passes', 'lower the similarity threshold until some results come back from the replica'], a: 1,
  e: 'An ungrounded answer is the dangerous failure here: fluent, uncitable and indistinguishable from a real one. Treat empty retrieval as an explicit branch, not an exception.' },
{ topic: 'prodops', q: 'Idempotency keys are needed most on...', o: ['read-only search and retrieval tool calls', 'tools with side effects', 'embedding calls that are repeated across many identical documents', 'any tool whose response takes longer than the configured request timeout'], a: 1,
  e: 'Reads repeat harmlessly. Writes, charges, emails and bookings do not, and queues deliver at least once, so the key belongs at the tool boundary.' },
{ topic: 'prodops', q: 'Which metric best explains "the feature is accurate but loses money"?', o: ['average cost per request measured across the whole month', 'cost per successful task', 'total token spend broken down by model and endpoint', 'the ratio of input tokens to output tokens on a typical request'], a: 1,
  e: 'Failures, retries and escalations are all paid for. At 70% success, a 4.00 request costs 5.71 per real result — and raising success usually beats shaving price.' },
{ topic: 'prodops', q: 'Users call the product slow although p95 total latency meets the target. Check...', o: ['throughput in requests per second during the reported period', 'time to first token', 'the p99 rather than the p95 of the same total latency metric', 'cache hit rate, since misses are what the complaints correspond to'], a: 1,
  e: 'Five seconds of blank screen and five seconds of streaming text feel completely different. Perceived latency is TTFT, and most dashboards never plot it.' },
{ topic: 'prodops', q: 'The strongest defence against indirect prompt injection is...', o: ['a classifier that screens retrieved documents before they enter the prompt', 'least-privilege tool scopes', 'instructing the model in the system prompt to ignore embedded commands', 'escaping and delimiting all retrieved content before adding it to the context'], a: 1,
  e: 'Screening and delimiting help and none of them are complete. Scoping the tools decides whether a successful injection is an embarrassment or an incident.' },
{ topic: 'prodops', q: 'A canary for an LLM release must gate on error rate, latency and...', o: ['the number of unique users who reached the new version', 'cost and quality metrics', 'CPU and memory headroom on the instances serving the canary', 'how long the canary has been running against production traffic'], a: 1,
  e: 'A version that is fast and cheap and quietly worse passes an infrastructure-only check. Token counts, refusal rate, escalation rate and judge scores belong in the gate.' },
{ topic: 'prodops', q: 'Your release manifest pins the model version and the prompt version. What is still missing?', o: ['the sampling temperature used for the completion call', 'the chunking and retrieval configuration', 'the region the provider endpoint was served from', 'the exact library version of the provider SDK in use'], a: 1,
  e: 'Re-chunking or re-embedding a corpus changes every answer while the model id stays identical. Without retrieval config in the manifest, a result is not reproducible.' }

]);
