/* ============================================================
   Study paths — what to learn, in what order, for which role.
   Each stage links to topics in this bank and to the interactive
   course in this repo that teaches the underlying idea properly.
   ============================================================ */
window.PATHS = [

{ n: 'Two weeks to an interview', i: '⏱️', c: 'var(--red)', time: '10 evenings',
  d: 'The compressed version. Covers what actually gets asked, in the order that lets each stage build on the last. If you only have one week, do stages 1, 2, 4 and 6 and skip the rest.',
  stages: [
    { n: 'Day 1-2 — the vocabulary', topics: ['foundations'],
      d: 'Tokens, embeddings, context windows, sampling parameters, the difference between prompting, RAG and fine-tuning. Every later answer leans on these, and getting one wrong early undermines everything after it.',
      course: ['GenAI Flow — chapters 1-5', '../genai_flow/index.html'] },
    { n: 'Day 3-4 — RAG, properly', topics: ['rag', 'vectors'],
      d: 'The single most-asked area for AI engineer roles. Chunking, hybrid search, reranking, evaluation, and the failure modes. Be able to say "retrieval quality is the product" and defend it.',
      course: ['GenAI Flow — RAG and Advanced RAG', '../genai_flow/index.html'] },
    { n: 'Day 5 — inference and cost', topics: ['inference'],
      d: 'Prefill versus decode, the KV cache, prompt caching, batching, quantisation, and the arithmetic of what a request costs. This is where senior candidates separate themselves.',
      course: ['GenAI Flow — Making it fast', '../genai_flow/index.html'] },
    { n: 'Day 6 — training and tuning', topics: ['training'],
      d: 'SFT, LoRA, QLoRA, DPO, RLHF, GRPO, distillation — and, more importantly, when NOT to fine-tune. The LoRA-versus-QLoRA comparison comes up constantly.',
      course: ['GenAI Flow — Fine-tuning menu', '../genai_flow/index.html'] },
    { n: 'Day 7 — agents', topics: ['agents', 'prompting'],
      d: 'The loop, tools, harness engineering, memory, multi-agent, and the failure playbook. Know why two agents on the same model differ.',
      course: ['Agentic AI Flow', '../agentic_ai_flow/index.html'] },
    { n: 'Day 8 — evaluation', topics: ['eval'],
      d: 'How you know it works. The eval pyramid, LLM-as-judge and its biases, RAGAS, A/B testing. Teams hire for this because most candidates cannot do it.',
      course: ['GenAI Flow — LLM as a judge', '../genai_flow/index.html'] },
    { n: 'Day 9 — production and safety', topics: ['production', 'safety'],
      d: 'Caching layers, routing, observability, guardrails, injection, tenant isolation. The questions that reveal whether you have shipped or prototyped.',
      course: ['AI System Design — Caching layers', '../ai_system_design_concepts/index.html'] },
    { n: 'Day 10 — mock rounds', topics: ['sysdesign', 'behavioural'],
      d: 'Two full mock interviews out loud, timed. The gap between "I know this" and "I can say this in ninety seconds" is the entire reason people fail interviews they were qualified for.',
      course: ['Projects walkthrough — two real systems', '../projects_walkthrough/index.html'] }
  ] },

{ n: 'GenAI Engineer', i: '🧠', c: 'var(--violet)', time: '4-6 weeks',
  d: 'For roles focused on building with models: prompting, RAG, fine-tuning and evaluation. Heavier on how the model works than on the infrastructure around it.',
  stages: [
    { n: '1. Foundations', topics: ['foundations'],
      d: 'Tokens, embeddings, context, sampling. Do not skip this even if it feels basic — a shaky answer here colours the whole interview.',
      course: ['GenAI Flow', '../genai_flow/index.html'] },
    { n: '2. Inside the model', topics: ['transformers'],
      d: 'Attention, feed-forward, residual stream, positional encoding, prefill versus decode. Be able to walk a block step by step and say what each part does.',
      course: ['GenAI Flow — One transformer block', '../genai_flow/index.html'] },
    { n: '3. Prompting and context', topics: ['prompting'],
      d: 'Few-shot, chain of thought, structured output, memory layers, context engineering. The practical craft.',
      course: ['GenAI Flow — Decoding controls', '../genai_flow/index.html'] },
    { n: '4. RAG end to end', topics: ['rag', 'vectors'],
      d: 'Chunking, embeddings, hybrid retrieval, reranking, evaluation, failure modes. The largest single area.',
      course: ['GenAI Flow — Chunking and Beyond RAG', '../genai_flow/index.html'] },
    { n: '5. Training and tuning', topics: ['training'],
      d: 'The full menu, and the judgement to know that most tickets asking for a fine-tune are really asking for retrieval.',
      course: ['GenAI Flow — Fine-tuning menu', '../genai_flow/index.html'] },
    { n: '6. Evaluation', topics: ['eval'],
      d: 'The pyramid, judges and their biases, RAGAS, online testing. Build an eval set for something you have made — it is the best interview story you can have.',
      course: ['GenAI Flow — LLM as a judge', '../genai_flow/index.html'] },
    { n: '7. Safety and shipping', topics: ['safety', 'production'],
      d: 'Guardrails, injection, cost, latency, observability.',
      course: ['AI System Design', '../ai_system_design_concepts/index.html'] }
  ] },

{ n: 'AI Engineer (production / platform)', i: '🚀', c: 'var(--cyan)', time: '5-7 weeks',
  d: 'For roles that own the system rather than the model: serving, cost, reliability, data pipelines and platform. Expect heavier system-design and operations questions.',
  stages: [
    { n: '1. Foundations, fast', topics: ['foundations'],
      d: 'Enough to be fluent. You will not be asked to derive attention, but you must be precise about tokens, context and sampling.',
      course: ['GenAI Flow', '../genai_flow/index.html'] },
    { n: '2. Inference and serving', topics: ['inference'],
      d: 'Prefill versus decode, KV cache, PagedAttention, continuous batching, quantisation, speculative decoding, parallelism. The core of the role.',
      course: ['AI System Design — Sharding & parallelism', '../ai_system_design_concepts/index.html'] },
    { n: '3. Caching and cost', topics: ['production'],
      d: 'Prompt caching, semantic caching, penetration, stampede, routing, budgets. Be able to do the cost arithmetic in your head.',
      course: ['AI System Design — Caching layers', '../ai_system_design_concepts/index.html'] },
    { n: '4. Data engineering', topics: ['data'],
      d: 'Ingestion pipelines, streaming, big files, deduplication, idempotency, freshness. Unglamorous and constantly asked about.',
      course: ['AI System Design — Big files, small RAM', '../ai_system_design_concepts/index.html'] },
    { n: '5. Retrieval at scale', topics: ['vectors', 'rag'],
      d: 'ANN indexes, sharding, filtering, hybrid search, the memory arithmetic at a billion vectors.',
      course: ['AI System Design — Vector indexes', '../ai_system_design_concepts/index.html'] },
    { n: '6. Reliability and observability', topics: ['production', 'safety'],
      d: 'Timeouts, rate limits, circuit breakers, fallbacks, tracing, alerts, incidents, tenant isolation.',
      course: ['Agentic AI Flow — Failure playbook', '../agentic_ai_flow/index.html'] },
    { n: '7. System design practice', topics: ['sysdesign'],
      d: 'Work through each design question out loud with a whiteboard, doing the arithmetic. That habit is what the round is testing.',
      course: ['AI System Design — Canonical designs', '../ai_system_design_concepts/index.html'] }
  ] },

{ n: 'RAG / Search specialist', i: '🔍', c: 'var(--green)', time: '3-4 weeks',
  d: 'For roles where retrieval quality IS the product. Goes deep on chunking, hybrid search, ranking and retrieval evaluation, and expects you to argue about them.',
  stages: [
    { n: '1. Embeddings and similarity', topics: ['vectors'],
      d: 'Cosine and its alternatives, normalisation, dimensionality, asymmetric models, Matryoshka truncation.',
      course: ['GenAI Flow — Embeddings', '../genai_flow/index.html'] },
    { n: '2. Lexical search', topics: ['vectors'],
      d: 'Inverted indexes, BM25 term by term, analyzers, Elasticsearch mechanics. This is the half candidates skip and interviewers probe.',
      course: ['AI System Design — Elasticsearch & BM25', '../ai_system_design_concepts/index.html'] },
    { n: '3. Chunking', topics: ['rag'],
      d: 'All six strategies, parent-child, contextual retrieval, late chunking. Be able to say which you would use for which corpus and why.',
      course: ['GenAI Flow — Chunking', '../genai_flow/index.html'] },
    { n: '4. Hybrid and ranking', topics: ['rag'],
      d: 'RRF, cross-encoder reranking, query rewriting, metadata filtering, MMR.',
      course: ['GenAI Flow — Advanced RAG', '../genai_flow/index.html'] },
    { n: '5. ANN at scale', topics: ['vectors'],
      d: 'HNSW, IVF, product quantisation, filtered search, sharding, the recall/latency dial.',
      course: ['AI System Design — Vector indexes', '../ai_system_design_concepts/index.html'] },
    { n: '6. Retrieval evaluation', topics: ['eval'],
      d: 'recall@k, MRR, nDCG, context precision, RAGAS, building an eval set. Non-negotiable for this role.',
      course: ['GenAI Flow — LLM as a judge', '../genai_flow/index.html'] },
    { n: '7. Freshness and operations', topics: ['data'],
      d: 'Ingestion, incremental updates, deletes, reconciliation, index versioning, multilingual.',
      course: ['AI System Design — Caching layers', '../ai_system_design_concepts/index.html'] }
  ] },

{ n: 'Agent engineer', i: '🤖', c: 'var(--amber)', time: '3-4 weeks',
  d: 'For roles building agents that take actions. Heavy on harness engineering, tools, safety and evaluation of trajectories rather than answers.',
  stages: [
    { n: '1. The loop and tools', topics: ['agents'],
      d: 'Think-act-observe, tool definitions, function versus tool calling, structured output. Write a bare loop by hand once — it is about forty lines and it teaches more than any framework.',
      course: ['Agentic AI Flow', '../agentic_ai_flow/index.html'] },
    { n: '2. Harness engineering', topics: ['agents', 'prompting'],
      d: 'Context assembly, observation shaping, error messages, stop conditions. Why two agents on the same model differ by thirty points.',
      course: ['Agentic AI Flow — Harness engineering', '../agentic_ai_flow/index.html'] },
    { n: '3. Memory and context', topics: ['prompting'],
      d: 'The four memory layers, consolidation, summarisation, trimming policy, and why an agent forgets everything at turn 50.',
      course: ['GenAI Flow — Mem0', '../genai_flow/index.html'] },
    { n: '4. Patterns and multi-agent', topics: ['agents'],
      d: 'ReAct, plan-and-execute, reflection, routing, supervisor/worker, human in the loop. Including when NOT to go multi-agent.',
      course: ['LangGraph', '../langgraph/index.html'] },
    { n: '5. Failure and reliability', topics: ['agents', 'production'],
      d: 'The eight-failure playbook, budgets, loop detection, idempotency, durable checkpointing.',
      course: ['Agentic AI Flow — Failure playbook', '../agentic_ai_flow/index.html'] },
    { n: '6. Safety', topics: ['safety'],
      d: 'Prompt injection, least privilege, egress control, memory poisoning, approval gates, sandboxing.',
      course: ['Agentic AI Flow — Guardrails & HITL', '../agentic_ai_flow/index.html'] },
    { n: '7. Agent evaluation', topics: ['eval'],
      d: 'Trajectory evaluation, task success against the END state, cost per successful task, deterministic tool mocks in CI.',
      course: ['Agentic AI Flow — Evaluating agents', '../agentic_ai_flow/index.html'] }
  ] },

{ n: 'LLMOps / inference', i: '⚡', c: 'var(--pink)', time: '4-5 weeks',
  d: 'For roles serving models rather than building applications on them. Expect GPU memory arithmetic, throughput tuning and capacity planning.',
  stages: [
    { n: '1. The forward pass', topics: ['transformers'],
      d: 'Enough architecture to reason about memory and compute: attention cost, KV cache size, GQA, the prefill/decode split.',
      course: ['GenAI Flow — One transformer block', '../genai_flow/index.html'] },
    { n: '2. Memory arithmetic', topics: ['inference'],
      d: 'Weights, KV cache and activations. Be able to compute whether a model fits on a given card, out loud, without a calculator.',
      course: ['AI System Design — Sharding & parallelism', '../ai_system_design_concepts/index.html'] },
    { n: '3. Serving mechanics', topics: ['inference'],
      d: 'PagedAttention, continuous batching, chunked prefill, speculative decoding, disaggregated serving, inference servers.',
      course: ['AI System Design — LLM serving & cost', '../ai_system_design_concepts/index.html'] },
    { n: '4. Parallelism', topics: ['inference', 'transformers'],
      d: 'Tensor, pipeline, data and expert parallelism, and which goes on which wire. Plus ZeRO for the training side.',
      course: ['AI System Design — Sharding & parallelism', '../ai_system_design_concepts/index.html'] },
    { n: '5. Quantisation', topics: ['inference'],
      d: 'GPTQ, AWQ, NF4, fp8, KV cache quantisation, and the quality cost of each.',
      course: ['GenAI Flow — Making it fast', '../genai_flow/index.html'] },
    { n: '6. Capacity and cost', topics: ['production'],
      d: 'Sizing from traffic, peak-to-average, utilisation, provisioned versus on-demand, autoscaling signals, cold starts.',
      course: ['AI System Design — Capacity & scale', '../ai_system_design_concepts/index.html'] },
    { n: '7. Operations', topics: ['production', 'data'],
      d: 'Observability, SLOs, incidents, rollouts, drift, and the pipelines that feed it all.',
      course: ['AI System Design — Operate it', '../ai_system_design_concepts/index.html'] }
  ] },

{ n: 'Complete beginner', i: '🌱', c: 'var(--txt-3)', time: '10-12 weeks',
  d: 'If you are coming from general software engineering or from data analysis. Builds the foundation properly before touching anything LLM-specific — the shortcut costs more time than it saves.',
  stages: [
    { n: '1. Python, properly', topics: [],
      d: 'Generators, comprehensions, error handling, project structure. Most AI engineering is ordinary Python done carefully.',
      course: ['Python Basics', '../python_basics/index.html'] },
    { n: '2. Machine learning fundamentals', topics: [],
      d: 'Train/test splits, overfitting, evaluation metrics, bias and variance. You need these to talk about evaluation credibly, and they are still the right tool for tabular problems.',
      course: ['ML Fundamentals', '../ml_fundamentals/index.html'] },
    { n: '3. Deep learning fundamentals', topics: [],
      d: 'Neurons, backpropagation, gradients, why deep networks train at all. Enough to make the transformer chapter make sense rather than being memorised.',
      course: ['DL Fundamentals', '../dl_fundamentals/index.html'] },
    { n: '4. How LLMs work', topics: ['foundations', 'transformers'],
      d: 'Tokens through to attention and generation. Now it will click rather than being a list of terms.',
      course: ['GenAI Flow', '../genai_flow/index.html'] },
    { n: '5. Building with them', topics: ['prompting', 'rag'],
      d: 'Prompting, RAG, and the frameworks. Build something small and real — a RAG system over documents you actually care about.',
      course: ['LangChain', '../langchain/index.html'] },
    { n: '6. Agents', topics: ['agents'],
      d: 'The loop, tools, memory, and the harness. Build one by hand before using a framework.',
      course: ['Agentic AI Flow', '../agentic_ai_flow/index.html'] },
    { n: '7. Making it real', topics: ['eval', 'production', 'safety'],
      d: 'Evaluation, cost, latency, guardrails, observability. This is what separates a portfolio project from something an employer recognises as engineering.',
      course: ['AI System Design', '../ai_system_design_concepts/index.html'] },
    { n: '8. Two worked systems', topics: ['sysdesign', 'behavioural'],
      d: 'Read two real systems end to end, then build your own and be able to talk about what it cost and how you knew it worked.',
      course: ['Projects walkthrough', '../projects_walkthrough/index.html'] }
  ] }

];
